### ISSUE TITLE
How to setup travis to work with `libvips`

### ISSUE THREAD

**Issue by GustavoCaso** [libvips/ruby-vips#137]
I'm having some problems trying to setup Travis to work ruby-vips for testing. I have checked the travis file from this repo but there a few things I do not understand. Is there any straightforward way of adding vips to the travis config file?

**Comment by jcupitt** [comment]
Hello, you need the libvips shared library on there, version 8.2 or later. Travis have a new container which might have a recent-enough one; if not, you'll need to build libvips from source before you start.

The ruby-vips .travis.yml builds each time, so you shloud just be able to copy-paste that.

**Comment by GustavoCaso** [comment]
Thanks
