### ISSUE TITLE
Wrong number of arguments for ffi find_type

### ISSUE THREAD

**Issue by dignoe** [libvips/ruby-vips#175]
While trying to `require 'vips'`, I get the following error:

    /Users/chad/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/mkmf.rb:1237:in `find_type': wrong number of arguments (given 1, expected 2+) (ArgumentError)
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ffi-1.9.23/lib/ffi/struct.rb:332:in `find_type'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ffi-1.9.23/lib/ffi/struct.rb:326:in `find_field_type'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ffi-1.9.23/lib/ffi/struct.rb:366:in `array_layout'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ffi-1.9.23/lib/ffi/struct.rb:278:in `layout'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ruby-vips-2.0.12/lib/vips/gobject.rb:45:in `block in included'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ruby-vips-2.0.12/lib/vips/gobject.rb:44:in `class_eval'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ruby-vips-2.0.12/lib/vips/gobject.rb:44:in `included'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ruby-vips-2.0.12/lib/vips/gobject.rb:54:in `include'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ruby-vips-2.0.12/lib/vips/gobject.rb:54:in `<class:ManagedStruct>'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ruby-vips-2.0.12/lib/vips/gobject.rb:53:in `<class:GObject>'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ruby-vips-2.0.12/lib/vips/gobject.rb:34:in `<module:GObject>'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ruby-vips-2.0.12/lib/vips/gobject.rb:10:in `<top (required)>'
	from /Users/chad/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	from /Users/chad/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	from /Users/chad/.rvm/gems/ruby-2.3.4/gems/ruby-vips-2.0.12/lib/vips.rb:157:in `<top (required)>'
	from /Users/chad/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Users/chad/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Users/chad/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from ./svg_to_png:8:in `<main>'

ruby-vips v2.0.12
ffi v1.9.23
ruby v2.3.4p301
vips v8.6.3

**Comment by jcupitt** [comment]
Hello @dignoe, sorry for the delay in responding. 

I tried with ruby2.5 and the same versions of the packages you are using and it seem to work for me (the test suite passes). I'll set up a ruby2.3 and see if that fails.

What platform are you using? Is that macos?

**Comment by jcupitt** [comment]
Looks like I can't build ruby2.3 on current Ubuntu -- ruby2.3 doesn't support recent openssl versions.

I'll try in a docker container.

**Comment by jcupitt** [comment]
It seems to work fine for me on Ubuntu with ruby2.3. 

```
john@yingna ~/GIT/nip2 (master) $ docker run -it ruby-vips-ruby2.3-ubuntu16.04:latest
root@feb021486777:/usr/local/src# irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> 
```

So it's probably a macOS issue. I have a mac at home, I'll try tonight if I have time.

**Comment by jcupitt** [comment]
I tried on my mac at home and it seems to work. 

```
john@katamata:~$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
john@katamata:~$ which ruby
/usr/bin/ruby
john@katamata:~$ which gem
/usr/bin/gem
john@katamata:~$ gem install ruby-vips --user
WARNING:  You don't have /Users/john/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.23
Fetching: ruby-vips-2.0.12.gem (100%)
Successfully installed ruby-vips-2.0.12
Parsing documentation for ffi-1.9.23
Installing ri documentation for ffi-1.9.23
Parsing documentation for ruby-vips-2.0.12
Installing ri documentation for ruby-vips-2.0.12
Done installing documentation for ffi, ruby-vips after 33 seconds
2 gems installed
john@katamata:~$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> 
```

So I think it has to be an issue with your ruby install.

**Comment by dignoe** [comment]
Thanks for testing that. I'll take another look.

**Comment by jcupitt** [comment]
Please reopen if this is still an issue.
