### ISSUE TITLE
Bump to 8.7.0

### ISSUE THREAD

**Issue by dannote** [libvips/ruby-vips#181]
Hello!

I'm affected by jcupitt/pyvips#39 when trying to load an `.ico` file.
Could you please also bump `ruby-vips` version to fix that?

**Comment by jcupitt** [comment]
Hello @dannote, ruby-vips should be fine, you just need an updated libvips. You can build the -rc1 version, or I plan to make it official very soon.

https://github.com/jcupitt/libvips/releases/tag/v8.7.0-rc1

**Comment by kleisauke** [comment]
If you can't build the -rc1 version yourself, you could try to patch ImageMagick [mime.xml](https://github.com/ImageMagick/ImageMagick6/blob/ba67f32f517b84125f4c5aa1330445ac4f482f6a/config/mime.xml), see:

```diff
diff --git a/config/mime.xml b/config/mime.xml
index 1111111..2222222 100644
--- a/mime.xml
+++ b/mime.xml
@@ -826,7 +826,7 @@
   <mime type="image/x-gzeps" description="EPS image (gzip-compressed)" priority="100" pattern="*.eps.gz" />
   <mime type="image/x-gzeps" description="EPS image (gzip-compressed)" priority="100" pattern="*.epsi.gz" />
   <mime type="image/x-gzeps" description="EPS image (gzip-compressed)" priority="100" pattern="*.epsf.gz" />
-  <mime type="image/x-ico" acronym="ICO" description="Windows Icon" priority="100" pattern="*.ico" />
+  <mime type="image/x-ico" acronym="ICO" description="Windows Icon" data-type="string" offset="0" magic="\00\00\01\00" priority="100" pattern="*.ico" />
   <mime type="image/x-icns" description="MacOS X icon" data-type="string" offset="0" magic="icns" priority="50" />
   <mime type="image/x-icns" description="MacOS X icon" priority="100" pattern="*.icns" />
   <mime type="image/x-iff" description="IFF image" priority="100" pattern="*.iff" />
```

(not tested, but should work, I think)

**Comment by jcupitt** [comment]
Oh nice, I didn't realize IM could get types that way.

**Comment by dannote** [comment]
@jcupitt That worked, thanks a lot!

**Comment by jcupitt** [comment]
8.7.0 is out now (finally) and we're testing against ot with Travis. I'll close.
