### ISSUE TITLE
LoadError: Could not open library 'glib-2.0'

### ISSUE THREAD

**Issue by mbajur** [libvips/ruby-vips#187]
Hello, this is continuation of an issue i opened on `image_processing` gem issue tracker ([link to original issue](https://github.com/janko-m/image_processing/issues/45)). Long story short: i am not able to use ruby-vips on `alpine` in any possible way. I've tried to set it up using [this](https://github.com/felixbuenemann/vips-alpine/blob/master/Dockerfile) and [this](https://github.com/codechimp-io/vips-alpine/blob/master/Dockerfile) Dockerfiles and also i tried to use apk packages and still no luck. It always ends up in:

```
Traceback (most recent call last):
	8: from app.rb:11:in `<main>'
	7: from app.rb:11:in `require'
	6: from /usr/local/bundle/gems/image_processing-1.7.1/lib/image_processing/vips.rb:1:in `<top (required)>'
	5: from /usr/local/bundle/gems/image_processing-1.7.1/lib/image_processing/vips.rb:1:in `require'
	4: from /usr/local/bundle/gems/ruby-vips-2.0.13/lib/vips.rb:13:in `<top (required)>'
	3: from /usr/local/bundle/gems/ruby-vips-2.0.13/lib/vips.rb:28:in `<module:GLib>'
	2: from /usr/local/bundle/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `ffi_lib'
	1: from /usr/local/bundle/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `map'
/usr/local/bundle/gems/ffi-1.9.25/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'glib-2.0': Error loading shared library glib-2.0: No such file or directory. (LoadError)
Could not open library 'libglib-2.0.so': Error loading shared library libglib-2.0.so: No such file or directory
```

I've also prepared a simple docker-based repo to make it able to reproduce it easily. To do so, you can clone it: https://github.com/mbajur/ruby-vips-example

and run:

```
docker build -t ruby-vips-example .
docker run --rm -ti ruby-vips-example bundle exec ruby app.rb
```

Please take note i can't be considered as an super experienced unix power-user. I know some stuff but that's probably not enough and it's highly possible i've did some really silly mistake in here - and i'm really sorry if so.

Thanks in advance!

**Comment by jcupitt** [comment]
Your dockerfile is using a testing (I think) alpine, not alpine latest. libvips is still not available via apk on alpine (I think), so I built from source.

**Comment by jcupitt** [comment]
Yes, I think you are mixing up alpine packages from edge and testing with regular alpine. Until vips (finally!) lands in alpine:latest, it's safest to build your own libvips (I think).

**Comment by mbajur** [comment]
Thank you! Following your example did the trick :)
