### ISSUE TITLE
Error generating thumbnails on Ubuntu 18.04

### ISSUE THREAD

**Issue by dkam** [libvips/ruby-vips#192]
I'm unable to generate thumbnails. I suspect there's a dependency not installed. 

```ruby
image = Vips::Image.new_from_file('70b18abf6682076f.jpeg')
image.thumbnail_image
Vips::Error (VipsOperation: class "thumbnail_image" not found)
```

```ruby
Vips::Image.thumbnail( '70b18abf6682076f.jpeg', 100, {} )
Vips::Error (VipsOperation: class "thumbnail" not found)
```

The command line thumbnail action doesn't work either which I suppose is the cause of the issue. The thumbnail binary is installed:

```bash
$ vips thumbnail
vips: unknown action "thumbnail"
$ vipsthumbnail -?
Usage:
  vipsthumbnail [OPTION…] - thumbnail generator
```

Ubuntu 18.04, libvips-tools, libvips-dev ,libtiff5-dev, libjpeg-turbo8-dev, libgsf-1-dev & libglib2.0-dev are installed.

**Comment by jcupitt** [comment]
Hello @dkam, Ubuntu 18.04 unfortunately bundles a very old libvips (8.4 I think? from 2016), 

You'll probably need to build your own, or use something like Docker to run a cross-platform binary. There's a dockerfile here to build 8.7.1 on 18.04 which might help:

https://github.com/jcupitt/docker-builds/tree/master/ruby-vips-libvips-ubuntu18.04

**Comment by dkam** [comment]
Awesome thanks very much!
