### ISSUE TITLE
Travis test on OSX

### ISSUE THREAD

**Issue by ioquatix** [libvips/ruby-vips#196]
Not sure if this is helpful but:

https://github.com/ioquatix/vips/blob/a2d2f10b965f3ef2f95de290dc0ba6472811a06c/.travis.yml#L40-L41

It could be useful to upstream.

**Comment by jcupitt** [comment]
I had a look, but your .travis.yml is now very different, and I don't know it well enough to make a call.

Do you think I should just copy-paste the whole thing?

**Comment by ioquatix** [comment]
I am building vips as part of the gem.... It’s basically the same thing, I’ll let you know if it ever breaks :)
