### ISSUE TITLE
Memory and disk IO spikes when reading/writing an image

### ISSUE THREAD

**Issue by linkyndy** [libvips/ruby-vips#197]
We've deployed a variant of our image processing algorithm with libvips in production and after several minutes, we've seen great spikes in memory and disk IO (see screenshots), going more and more often to 100%. We had to rollback this implementation.

![disk IO spikes](https://user-images.githubusercontent.com/319844/59264285-11bff100-8c43-11e9-98c6-7e0e240fd0a9.png)
_disk IO spikes_
![memory spikes](https://user-images.githubusercontent.com/319844/59264286-11bff100-8c43-11e9-9e21-69d0628f2b6e.png)
_memory spikes_

As you can see, spikes went really bad between when the deployed happened (around 15:20), and when the rollback happened (around 17:00). The calmer periods occurred because we lowered the number of threads per background worker that processes such jobs. In the end we got to 1 thread/worker, which is clearly not enough for us, and still, spikes started again.

Now I am trying to make sense of all this; hopefully, you can shed some more light onto what exactly might cause these spikes, or what would viable contexts be that could cause this. Our implementation is this:

```ruby
image = Vips::Image.new_from_file(filename)
image = image.colourspace(:srgb)
image = image.flatten(background: [255, 255, 255]) if image.has_alpha?

pixels_pointer = image.write_to_memory
hash_result_pointer = FFI::MemoryPointer.new(:uint8, HASH_SIZE)

result = CLibrary(pixels_pointer, image.width, image.height, ..., hash_result_pointer)
hash_result_pointer.read_array_of_uint8(HASH_SIZE)
```

As comparison, our previous/current implementation does the same, only in Python, using Pillow to read, convert and flatten the image, and numpy/ctypes to export the image to an array and then make it available to the C library. This implementation doesn't have any memory/disk IO issues (it also doesn't use libvips, but imagemagick).

So, I am more looking into what can cause this with libvips. What could cause the spikes? Reading the images? Writing them to memory? How are these operations handles by libvips? Maybe if I get a better understanding of the inner workings of libvips, I can pinpoint the problem with our implementation.

Thank you!

**Comment by jcupitt** [comment]
Ouch! That looks bad.

You need to set `access: :sequential` on `new_from_file`. This will make libvips stream from the file source into your memory buffer. If you don't set this hint, libvips will open the image in random access mode, and this will use a lot of memory, or for large images, a lot of disc.

Second, do you know what file formats are being loaded? libvips will probably load unknown formats with libMagick, which will use a lot of disc and memory. I'd check what formats you have built your libvips binary to be able to handle natively, and what formats it is deferring to libMagick for.

**Comment by jcupitt** [comment]
This chapter in the docs explains how `new_from_file` works and what the access hint means:

https://libvips.github.io/libvips/API/current/How-it-opens-files.md.html

**Comment by linkyndy** [comment]
Thanks for your fast answer!

I will try `sequential` today. Regarding formats, we only allow (for now) .jpg, .gif, .bmp, .tif and .png (the very majority is .jpg).

**Comment by jcupitt** [comment]
A 20mb jpg can be > 400mb when decompressed, so you can see big spikes even with smaller images. You can make a 20mb TIFF that expands to any size you like, of course, they can easily be 100s of GB (a "decompression bomb").

I would add a limit on image dimensions too, perhaps change your code to be:

```ruby
image = Vips::Image.new_from_file filename, access: :sequential
raise "some exception" if image.width > 10000 || image.height > 10000
```

libvips delays pixel decode until the first pixel access, so it's quick to check dimensions after open.

libvips does not support BMP directly -- it loads it via libMagick. You'll see big spikes for large BMP even with `access: :sequential`.

The GIF loader in libvips 8.8.0 needs much less memory, if you're not using that.

Could you paste `configure` output for your libvips build?

**Comment by linkyndy** [comment]
Seems that `sequential` access solved most of these spikes! Thanks for the tip!

> I would add a limit on image dimensions too, perhaps change your code to be:

That's a good point, I will add that check 🙌
 
> The GIF loader in libvips 8.8.0 needs much less memory, if you're not using that.

We are using 8.8.0.

> Could you paste `configure` output for your libvips build?

Here it is:

```
* build options
native win32:				no
native OS X:				no
open files in binary mode: 		no
enable debug:				no
enable deprecated library components:	yes
enable docs with gtkdoc:		no
gobject introspection: 			no
enable radiance support: 		yes
enable analyze support: 		yes
enable PPM support: 			yes

* optional dependencies
use fftw3 for FFT: 			yes
Magick package: 			MagickCore
Magick API version: 			magick6
load with libMagick: 			yes
save with libMagick: 			yes
accelerate loops with orc: 		yes
  (requires orc-0.4.11 or later)
ICC profile support with lcms: 		yes (lcms2)
file import with niftiio: 		no
file import with libheif: 		no
file import with OpenEXR: 		yes
file import with OpenSlide:		yes
  (requires openslide-3.3.0 or later)
file import with matio: 		yes
PDF import with PDFium 			no
PDF import with poppler-glib: 		no
  (requires poppler-glib 0.16.0 or later)
SVG import with librsvg-2.0: 		yes
  (requires librsvg-2.0 2.34.0 or later)
zlib: 					yes
file import with cfitsio: 		yes
file import/export with libwebp:	yes
  (requires libwebp, libwebpmux, libwebpdemux 0.5.0 or later)
text rendering with pangoft2: 		no
file import/export with libpng: 	yes (pkg-config libpng >= 1.2.9)
  (requires libpng-1.2.9 or later)
support 8bpp PNG quantisation:		no
  (requires libimagequant)
file import/export with libtiff:	yes (pkg-config libtiff-4)
file import/export with giflib:		yes (found by search)
file import/export with libjpeg:	yes (pkg-config)
image pyramid export:			yes
  (requires libgsf-1 1.14.26 or later)
use libexif to load/save JPEG metadata: yes
```

**Comment by jcupitt** [comment]
You configure looks OK, good!

You could change your policy.xml for imagemagick to prioritize disc or memory for BMP load, I expect you know.

**Comment by linkyndy** [comment]
So, `access: :sequential` mostly reduced memory and disk spikes. We still have a few and for that, I want to limit image size; hopefully that would solve everything (related to this). Thanks a million!

**Comment by jcupitt** [comment]
Good! Is it an improvement over your previous implementation?

**Comment by linkyndy** [comment]
Over the non-libvips one? Certainly! CPU went a lot down and image processing times are 60% faster.

**Comment by jcupitt** [comment]
I'm glad it worked out!
