### ISSUE TITLE
image.write_to_memory raises FFI::NullPointerError sometimes

### ISSUE THREAD

**Issue by linkyndy** [libvips/ruby-vips#199]
We've noticed on our production machines that a `FFI::NullPointerError` is raised sometimes when we try to `image.write_to_memory` (sometimes, as in, an error per minute, at a rate of a few dozen thousand jobs per minute). 

I see this raised for `.jpg`s, but also for `.tif`s and `.png`s. This is the relevant backtrace:

```
/.../vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.13/lib/vips/image.rb:486:in `get_bytes'
/.../vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.13/lib/vips/image.rb:486:in `write_to_memory'
```

I thought this could be because the images we try to write are too big, however we've limited the file size/resolution of the images we process, and judging by our memory/disk graphs, this shouldn't be the case.

Sorry for opening so many issues, but hopefully some of them trigger some ideas of improvement on your side as well ✌️

**Comment by jcupitt** [comment]
Try changing `write_to_memory` to be:

```ruby
    def write_to_memory
      len = Vips::SizeStruct.new
      ptr = Vips::vips_image_write_to_memory self, len
      raise Vips::Error if ptr == nil

      # wrap up as an autopointer
      ptr = FFI::AutoPointer.new(ptr, GLib::G_FREE)

      ptr.get_bytes 0, len[:value]
    end
```

ie. check for a NULL return. You should get a more helpful error message.

**Comment by linkyndy** [comment]
Will this give more details about the underlying C error? Referring to the ones over [here](https://github.com/libvips/libvips/blob/master/libvips/iofuncs/image.c#L2673).

**Comment by jcupitt** [comment]
OK, 2.0.15 is out with this improvement. I'll close.
