### ISSUE TITLE
Weird SVG text scaling

### ISSUE THREAD

**Issue by hschne** [libvips/ruby-vips#201]
I am trying to create a high resolution PNG from a small SVG using multiple loads, as suggested [here](https://github.com/libvips/ruby-vips/issues/103). Unfortunately, using `Vips::Image.svgload_buffer(data, scale: 3)` results in the text in that SVG being blown up a fair bit. 

![testfile](https://user-images.githubusercontent.com/5294464/62694322-67f7a900-b9d4-11e9-8436-83cfd1f09022.png)

The original SVG in question can be found on [Filebin](https://filebin.net/h82x03bmrr24b77b/chart.svg?t=nfukoayg). Running `vips svgload infile.svg outfile.svg` yields this: 

![chart](https://user-images.githubusercontent.com/5294464/62694866-72667280-b9d5-11e9-9534-366c6aee6957.png)

The code I use to render the PNG looks something like this. 

```
data = IO.binread(File.expand_path('infile.svg))
image = Vips::Image.svgload_buffer(data)
if image.width < 1500 || image.height < 1500
  smaller = image.width < image.height ? image.width : image.height
  scale = 1500 / smaller
  image = Vips::Image.svgload_buffer(data, scale: scale)
end
image.write_to_file('outfile.png')

```

I already tried using `image.resize(...)` after the initial load, but that results in a blurry image. 

Running `vipsthumbnail chart.svg --size 1500` also yields an image with the wrong text size, so I'm guessing this is an issue with libvips. 

I'm still raising this here, because I would like a solution specific to ruby-vips (since that is where I'm trying to accomplish that whole resizing thing). 

I'm running the following versions: 
- ruby-vips-2.0.13
- vips-8.7.4
- librsvg - 2.44.14

Any help would be appreciated :)

**Comment by jcupitt** [comment]
Hello @hschne,

This is a librsvg issue -- people have been having problems in sharp as well, eg.:

https://github.com/lovell/sharp/issues/1460

It sounds like reverting to 2.40 fixes it, or forward to 2.45.5.

You can reproduce your problem at the command-line with:

```
vips svgload chart.svg x.png
vips svgload chart.svg x.png --scale 2
```

etc., it might make testing easier.

**Comment by jcupitt** [comment]
I wouldn't use `svgload_buffer` in this case -- loading from the file should be faster and use less memory.

**Comment by hschne** [comment]
Thanks a bunch for the quick help! I'll upgrade librsvg then.

Also thanks for the heads up regarding performance!
