### ISSUE TITLE
stray v8.8.* tags?

### ISSUE THREAD

**Issue by jcupitt** [libvips/ruby-vips#206]
Hi @ioquatix, I noticed there are some tags which seem to use a different version numbering, for example:

https://github.com/libvips/ruby-vips/releases/tag/v8.8.0.3

If you download that zip, it's actually 2.0.13. There are some others:

```

john@kiwi:~/GIT/ruby-vips (master)$ git checkout v
v0.1.1     v0.3.14    v0.3.8     v1.0.5     v2.0.13    v2.0.7     v8.7.0.1 
v0.2.0     v0.3.2     v0.3.9     v1.0.6     v2.0.14    v2.0.8     v8.8.0.1 
v0.2.1     v0.3.3     v1.0.0     v2.0.0     v2.0.2     v2.0.9     v8.8.0.2 
v0.3.0     v0.3.4     v1.0.1     v2.0.1     v2.0.3     v8.6.3     v8.8.0.3 
v0.3.1     v0.3.5     v1.0.2     v2.0.10    v2.0.4     v8.6.3.1   
v0.3.12    v0.3.6     v1.0.3     v2.0.11    v2.0.5     v8.6.3.2   
v0.3.13    v0.3.7     v1.0.4     v2.0.12    v2.0.6     v8.7.0     
```

This is causing confusion for Debian -- their ruby-vips package 2.0.13-1 is tagged as outdated because their release bot thinks 8.8.0.3 is available.

https://tracker.debian.org/pkg/ruby-vips

Should we remove these tags?

**Comment by ioquatix** [comment]
I'm not sure why this decision involves me, do you mind clarifying that?

**Comment by jcupitt** [comment]
Oh, didn't you add these? The tags page says:

```
v8.8.0.3 @ioquatix ioquatix tagged this on 11 Jun · 13 commits to master since this tag
```

**Comment by ioquatix** [comment]
Oh... that looks like a mistake on my part. I'll investigate it and why it happened.

**Comment by ioquatix** [comment]
Okay, that was very odd, I don't believe I ever intended to push those tags to this repo.

I track both this repo and my own fork which compiles libvips in the gem itself.

Because of that, I version the gem according to the libvips version. That's why I have those tags. But they should never have come into this repo. My apologies for that.

I've removed them all.

**Comment by jcupitt** [comment]
Thanks!
