### ISSUE TITLE
Vips::Interpretation doc mistake

### ISSUE THREAD

**Issue by D-W-L** [libvips/ruby-vips#210]
Hi,
in class: Vips::Interpretation the value :b_w is not valid, as cited in the documentation. It give the error message
`/usr/lib/ruby/vendor_ruby/vips/gvalue.rb:33:in `from_nick': ruby-vips: enum 'VipsInterpretation' has no member 'b_w', should be one of: error, multiband, b-w, histogram, xyz, lab, cmyk, labq, rgb, cmc, lch, labs, srgb, yxy, fourier, rgb16, grey16, matrix, scrgb, hsv (Vips::Error)
`
The parameter has to be 'b-w' or :'b-w'

**Comment by jcupitt** [comment]
Oh yes, how silly. I've added a thing to map `_` to `-` in enum names. 

Thanks for reporting this! It'll be fixed in the next version.
