### ISSUE TITLE
Could not open library 'libglib-2.0.so.0.so'

### ISSUE THREAD

**Issue by linkyndy** [libvips/ruby-vips#212]
Hello,

I've tried using the `2.0.16` version of this gem on Ruby `2.5.5` (combined with libvips `8.8.3` on an Alpine Docker container, if it helps) and I get the following error:

```
Traceback (most recent call last):
	24: from /usr/local/bin/bundle:22:in `<main>'
	23: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	22: from /usr/local/bin/bundle:30:in `block in <main>'
	21: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
	20: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	19: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
	18: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	17: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	16: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	15: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:494:in `console'
	14: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/console.rb:15:in `run'
	13: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:114:in `require'
	12: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `require'
	11: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `each'
	10: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
	 9: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `each'
	 8: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	 7: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `require'
	 6: from /app/vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.16/lib/ruby-vips.rb:1:in `<top (required)>'
	 5: from /app/vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.16/lib/ruby-vips.rb:1:in `require'
	 4: from /app/vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.16/lib/vips.rb:36:in `<top (required)>'
	 3: from /app/vendor/bundle/ruby/2.5.0/gems/ruby-vips-2.0.16/lib/vips.rb:45:in `<module:GLib>'
	 2: from /app/vendor/bundle/ruby/2.5.0/gems/ffi-1.11.1/lib/ffi/library.rb:99:in `ffi_lib'
	 1: from /app/vendor/bundle/ruby/2.5.0/gems/ffi-1.11.1/lib/ffi/library.rb:99:in `map'
/app/vendor/bundle/ruby/2.5.0/gems/ffi-1.11.1/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'glib-2.0.so.0': Error loading shared library glib-2.0.so.0: No such file or directory. (LoadError)
Could not open library 'libglib-2.0.so.0.so': Error loading shared library libglib-2.0.so.0.so: No such file or directory
```

I assume it has to do with the [latest changes](https://github.com/libvips/ruby-vips/commit/0530df59d37b12a467661aaf001c045dd10795dd) with regards to generating libnames.

**Comment by Nakilon** [comment]
Asking just to be sure: have you already successfully used the gem with your Docker image?  
Since it depends on a plenty of stuff: https://github.com/felixbuenemann/vips-alpine/blob/master/Dockerfile

**Comment by jcupitt** [comment]
Hello @linkyndy,

Well, that looks bad: `libglib-2.0.so.0.so`

I'll see if I can reproduce the problem in a docker container.

**Comment by jcupitt** [comment]
Yes, I see this in a container as well:

https://github.com/jcupitt/docker-builds/blob/master/ruby-vips-alpine/Dockerfile

Here's what seems to be happening:

- ruby-vips wants to open library `glib-2.0`, API number 0
- on linux, ruby-vips `library_name` turns this into `glib-2.0.so.0`
- ffi_lib calls `map_library_name` to turn this into a platform native name
- this adds a `lib` prefix to make `libglib-2.0.so.0` (the correct name)
- it also adds an extra `.so` suffix in error if `FFI::Platform::IS_GNU` is not `true`

https://github.com/ffi/ffi/blob/master/lib/ffi/library.rb#L50

So it looks like Alpine is not GNU enough for ffi, I think. Looking at `IS_GNU` it's:

https://github.com/ffi/ffi/blob/master/lib/ffi/platform.rb#L91

```ruby
    IS_GNU = defined?(GNU_LIBC)
```

So I think this is an FFI bug: they should not add that extra suffix on Alpine.

**Comment by jcupitt** [comment]
What do you think @linkyndy? We could try opening an issue on ruby ffi. Perhaps they need an `IS_MUSL`?

**Comment by linkyndy** [comment]
I tested with both `2.0.15` and `2.0.16` of this gem, using the same setup, and everything is fine with the former. That's why I stopped my investigation here and didn't go to FFI. If you checked more things (thanks for that!) and feel it belongs to FFI, sure, I can pass this along.

**Comment by jcupitt** [comment]
I think it only worked on Alpine with ruby-vips 2.0.15 if you had the `glib-dev` package installed. 

Without that package, there's no `libglib-2.0.so` link, and it would have failed to find the library.

**Comment by linkyndy** [comment]
Both gem versions were tested with the following installed on an Alpine container:

```
RUN apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community/ \
  build-base \
  curl-dev \
  nano \
  libffi-dev \
  vips-dev
```

So, I would assume the dependencies were the same 🤔

**Comment by jcupitt** [comment]
`vips-dev` will have pulled in `glib-dev`. If you try with just `vips` I think it'll fail (I think).

**Comment by jcupitt** [comment]
I made an issue here: https://github.com/ffi/ffi/issues/727

**Comment by linkyndy** [comment]
Thanks a lot @jcupitt for your very quick action! Looking forward to this being resolved 😊

**Comment by jcupitt** [comment]
The very helpful @larskanis has changed ffi to hopefully fix this.

I'll close -- please open a new issue if you run into more problems.

**Comment by larskanis** [comment]
ffi-1.11.2 should fix this issue.
