### ISSUE TITLE
Can't reproduce watermark example

### ISSUE THREAD

**Issue by DanielSuarezCaceres** [libvips/ruby-vips#213]
I tried to mimick the watermark example that is in the doc (ruby-vips/example/watermark.rb) but I get method missing error with some of the functions.

For example, that line is ok:

`im = Vips::Image.new_from_file ARGV[0], access: :sequential`

But other functions like replicate or rotate doesn't work (triggers method missing error)

`text = text.gravity :centre, 200, 200
text = text.replicate 1 + im.width / text.width, 1 + im.height / text.height`

This is the error it shows: `VipsOperation: class "gravity" not found`

The same  with replicate or rotate methods, for example. I checked my image while debugging and, in fact, if I do: `my_image.methods`, none of the previous ones appears (gravity, replicate or rotate). I also checked ruby-vips/lib/vips/image.rb and the methods aren't there.

Any idea?

Thank you in advance

**Comment by jcupitt** [comment]
Hello @DanielSuarezCaceres, 

ruby-vips is a very "thin" binding. It doesn't have many functions itself, instead it just presents the functions available in the underlying libvips shared library via introspection.

My guess is that your libvips is too old. `gravity` was added in version 8.6, for example.

**Comment by DanielSuarezCaceres** [comment]
I thought it should be something like that, although my version is not too old I think (8.4.5)

Thank you for answering!
