### ISSUE TITLE
Can't find the `crop` method docs

### ISSUE THREAD

**Issue by Nakilon** [libvips/ruby-vips#217]
Either I'm blind or there is some bug that lists it in docs twice under the same alias `extract_area`: https://github.com/libvips/ruby-vips/blob/2c3d1539d5cb449e7fc17966dc0b89ee428242d5/lib/vips/methods.rb#L378-L394

Spent half an hour looking for the method `crop` that was used in some discussions. Would cmd+F it much faster find it either was:
```
Extract (crop) an area from an image.
```
instead of
```
Extract an area from an image.
```
or if it's really a bug that might need to be fixed.

**Comment by jcupitt** [comment]
Oh yes, the alias is broken. I'm sure that used to work. I'll fix it.

**Comment by jcupitt** [comment]
All done, thank you for reporting this, Nakilon.
