### ISSUE TITLE
Can't render "DIN Condensed" font

### ISSUE THREAD

**Issue by Nakilon** [libvips/ruby-vips#218]
The following code renders 26 chars as PNGs:

```ruby
chars = %w{
  Courier
  DIN\ Condensed
  Verdana
}.flat_map do |font|
  FileUtils.mkdir_p "chars/#{font}"
  (?A..?Z).map do |char|
    filename = "chars/#{font}/#{char.ord}.png"
    Vips::Image.text(char, font: font, width: 100, height: 100).invert.write_to_file filename unless File.exist? filename
    [DHashVips::IDHash.fingerprint(filename), char]
  end
end
```

![image](https://user-images.githubusercontent.com/2870363/71750957-11ab6b00-2e8b-11ea-9d77-bafffac17e70.png)

But for "DIN Condensed" it seems to fallback to Verdana or smth:

![image](https://user-images.githubusercontent.com/2870363/71751022-44edfa00-2e8b-11ea-8fb8-30a66c28f9ec.png)

![image](https://user-images.githubusercontent.com/2870363/71751012-3acbfb80-2e8b-11ea-8ddf-a11b9e0a7aea.png)

It should look like this:

![image](https://user-images.githubusercontent.com/2870363/71750818-a497d580-2e8a-11ea-84aa-0ca9c30770f5.png)

Maybe it's because of " " in the font name?

UPD: the link "font : gchararray, font to render with" at https://libvips.github.io/libvips/API/current/libvips-create.html has interesting path -- https://libvips.github.io/usr/share/gtk-doc/html/gobject/gobject-Standard-Parameter-and-Value-Types.html#gchararray

UPD2: `fontfile: "/Library/Fonts/DIN Condensed Bold.ttf"` does not help.
BTW, other fonts have other types: `/System/Library/Fonts/Courier.dfont`, `/System/Library/Fonts/Menlo.ttc`. But Arial and Tahoma are .ttf too and they are fine.

**Comment by jcupitt** [comment]
I don't think it's spaces -- for example, I can do:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.text("hello!!", font: "Lovers Quarrel", dpi: 300)
=> #<Image 85x30 uchar, 1 bands, multiband>
irb(main):003:0> x.write_to_file("x.png")
=> nil
```

To make:

![x](https://user-images.githubusercontent.com/580843/71767791-ea46b380-2f07-11ea-9e02-78838251f377.png)

**Comment by jcupitt** [comment]
`fontfile` adds the font but does not select it. Have you tried:

```
Vips::Image.text "hello world!", fontfile: "/Library/Fonts/DIN Condensed Bold.ttf"", font: "DIN Condensed Bold", dpi: 300
```

**Comment by Nakilon** [comment]
```ruby
chars = [
  ["DIN Condensed", "/Library/Fonts/DIN Condensed Bold.ttf"],
].flat_map do |font, fontfile|
...
    Vips::Image.text(char, font: font, fontfile: fontfile, width: 100, height: 100).invert.write_to_file filename unless File.exist? filename
...
end
```
didn't help.

Also tried to append "Bold" but it's looks like Verdana Bold.

![image](https://user-images.githubusercontent.com/2870363/71768447-073eaf00-2f27-11ea-9569-1ea4bfd70ae7.png)

Don't you have this font on your macOS?

**Comment by kleisauke** [comment]
Pango defaults to the CoreText rendering and mapping backend on macOS. You could try to use the Fontconfig backend with the `PANGOCAIRO_BACKEND="fontconfig"` environment variable.

**Comment by Nakilon** [comment]
> `PANGOCAIRO_BACKEND="fontconfig"` environment variable

Should I try to use it while installing the gem or libvips? In runtime it does not seem to help. Both with `:fontfile` and without.

**Comment by kleisauke** [comment]
It's a runtime variable, so you don't need to reinstall libvips. Perhaps you need also to set the `FONTCONFIG_PATH=/Library/Fonts` environment variable. You could debug if it maps the font name to the correct font file with:
```bash
FONTCONFIG_PATH=/Library/Fonts fc-match 'DIN Condensed'
```

I guess it should output something like this:
```bash
DIN Condensed.ttf: "DIN Condensed" "Regular"
```

Or to find a list of candidate names, you could try this:
```bash
FONTCONFIG_PATH=/Library/Fonts fc-list
```

(Unfortunately, I don't currently have any macOS system to test it on)

You can also try to manually rebuild the font cache with:
```bash
fc-cache -v
```

But this is probably only needed when new fonts are added to the system (I guess `DIN Condensed` is already pre-installed on macOS).

**Comment by jcupitt** [comment]
I tried in nip2 on macos and it works fine, so I think it's something to do with the way fontconfig is being built by homebrew.

I had a look at gtk-osx and they just buyild with:

```
  <tarball id="fontconfig" version="2.8.0">
    <pkg-config>fontconfig.pc</pkg-config>
    <source href="http://www.fontconfig.org/release/fontconfig-2.8.0.tar.gz"
            hash="sha256:fa2a1c6eea654d9fce7a4b1220f10c99cdec848dccaf1625c01f076b31382335"
            md5sum="77e15a92006ddc2adbb06f840d591c0e" size="1548409"/>
    <dependencies>
      <dep package="expat"/>
    </dependencies>
  </tarball>
```

So no strange flags.

**Comment by jcupitt** [comment]
I spoke too soon -- while fonts appear in the interface, `text` in nip2 is still unable to render them.

**Comment by Nakilon** [comment]
This is what it says:
```
$ FONTCONFIG_PATH=/Library/Fonts fc-match 'DIN Condensed'
DIN Condensed Bold.ttf: "DIN Condensed" "Bold"
```
```
$ FONTCONFIG_PATH=/Library/Fonts fc-list | grep DIN
/Library/Fonts/DIN Alternate Bold.ttf: DIN Alternate:style=Bold
/Library/Fonts/DIN Condensed Bold.ttf: DIN Condensed:style=Bold`
```
And I don't remember to add any fonts to the system manually, and it's pretty fresh.

Tried right now both with and without `fontfile` and with both variables `FONTCONFIG_PATH=/Library/Fonts PANGOCAIRO_BACKEND=fontconfig` -- still looks like Verdana and Verdana Bold.

**Comment by kleisauke** [comment]
The output of those commands looks OK. I tried to reproduce this on my Fedora machine and noticed that there is also a `pango-list` and `pango-view` command. I installed the `d-din-condensed-fonts` package and ran:
```bash
$ pango-list | grep DIN
D-DIN Condensed 
  Regular:           D-DIN Condensed, Condensed
  DINCondensed-Bold: D-DIN Condensed, Bold Condensed
  *Italic:           D-DIN Condensed, Italic
  *Bold Italic:      D-DIN Condensed, Bold Italic
$ pango-view --font 'D-DIN Condensed Bold' --no-display --text 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' --output out.png 
$ pango-view --font 'D-DIN Condensed, Bold' --no-display --text 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' --output out2.png 
```

Output:
![out](https://user-images.githubusercontent.com/12746591/71770263-158eca00-2f2b-11ea-8f96-da3a5eb36285.png)
![out2](https://user-images.githubusercontent.com/12746591/71770264-17588d80-2f2b-11ea-9c70-490d8e79d040.png)

So, perhaps you need to use `DIN Condensed, Bold` instead of `DIN Condensed Bold`.

**Comment by Nakilon** [comment]
> So, perhaps you need to use `DIN Condensed, Bold` instead of `DIN Condensed Bold`

It works! Thanks.

**Comment by kleisauke** [comment]
Great, glad it's working now. Out of curiosity, does it also render with `PANGOCAIRO_BACKEND=fontconfig`? It might produce a crisper text according to [Inkscape](http://bazaar.launchpad.net/~tghs/inkscape/0.92.x_mac_packaging/revision/15371).

**Comment by Nakilon** [comment]
I don't see much difference.
![image](https://user-images.githubusercontent.com/2870363/71771697-9f04c300-2f50-11ea-9337-6f30f91d76c5.png)
![image](https://user-images.githubusercontent.com/2870363/71771744-5dc0e300-2f51-11ea-87b4-caf7bdbde802.png)
![image](https://user-images.githubusercontent.com/2870363/71771797-fbb4ad80-2f51-11ea-97a6-222e58d72fad.png)
![image](https://user-images.githubusercontent.com/2870363/71771779-d6c03a80-2f51-11ea-9be4-26d73cb918b6.png)

**Comment by Nakilon** [comment]
I guess it can be closed unless you want to make something to make it easier to find the correct name for a font. Not sure if it would be possible or relevant to vips, though.
