### ISSUE TITLE
OpenBSD: Could not open library 'libglib-2.0.so.0': File not found

### ISSUE THREAD

**Issue by ghost** [libvips/ruby-vips#221]
Getting `LoadError (Could not open library 'glib-2.0.so.0': File not found. Could not open library 'libglib-2.0.so.0': File not found)` here on OpenBSD. How to tell ruby-vips to look for `/usr/local/lib/libglib-2.0.so.4201.2` instead?

Thanks.

**Comment by jcupitt** [comment]
Hello @1234dev,

I think Ruby ffi is expecting there to be a symlink meaning "glib-2.0 API version 0", ie. a link from libglib-2.0.so.0 to whatever binary you have. You'll need a similar link for libvips.so.42 as well.

I don't know much about the OpenBSD linker -- how does it handle ABI back compatibility? You might need to ask the Ruby ffi maintainer (they are very helpful) to make some adjustments to their library finder.

**Comment by 1234dev** [comment]
Thanks @jcupitt!

**Comment by jcupitt** [comment]
So perhaps the problem is with the openbsd glib package. Why is there no link for `libglib-2.0.so.0`?

**Comment by basicfeatures** [comment]
Looks like a port was created not too long after this issue:

https://openports.se/graphics/libvips

**Comment by basicfeatures** [comment]
Install libvips and its dependencies:
```
pkg_add libvips
pkg_add glib
pkg_add gobject-introspection
```

Symlink the OpenBSD binaries with what ruby-vips expects as of 2022.06.30:
```
ln -s /usr/local/lib/libvips.so.0.0 /usr/local/lib/libvips.so.42
ln -s /usr/local/lib/libglib-2.0.so.4201.6 /usr/local/lib/libglib-2.0.so.
ln -s /usr/local/lib/libgobject-2.0.so.4200.13 /usr/local/lib/libgobject-2.0.so.0
```

Cc: https://github.com/ffi/ffi/issues/738

**Comment by jcupitt** [comment]
Oh, great! Thanks for the update @basicfeatures.

You probably don't need `gobject-introspection`, fwiw.
