### ISSUE TITLE
at_least_libvips? returns false negative with libvips installed from source

### ISSUE THREAD

**Issue by vi-solutions** [libvips/ruby-vips#223]
I'm using with image_processing gem which requires vips >= 8.6. Since Ubuntu 18.04 only comes with 8.4 I had to build vips from source. `at_least_libvips?(8, 6)` returns `false` even though `8.10.0` is installed.

<img width="270" alt="Screen Shot 2020-03-19 at 11 50 12 AM" src="https://user-images.githubusercontent.com/57605013/77103616-ef2fe500-69d7-11ea-8a14-1b960e8a5c07.png">

<img width="337" alt="Screen Shot 2020-03-19 at 11 52 47 AM" src="https://user-images.githubusercontent.com/57605013/77103773-328a5380-69d8-11ea-99be-044e32e1de6a.png">

<img width="373" alt="Screen Shot 2020-03-19 at 11 58 36 AM" src="https://user-images.githubusercontent.com/57605013/77104313-10dd9c00-69d9-11ea-8a92-5088b33be7c9.png">

**Comment by jcupitt** [comment]
Hello @vi-solutions,

Your ruby-vips is probably picking up the wrong version of the library.

Try:

```
john@kiwi:~/GIT/libvips (master)$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> Vips::version_string
=> "8.10.0-Thu Mar 19 18:43:23 UTC 2020"
irb(main):003:0> Vips::at_least_libvips? 8, 10
=> true
irb(main):004:0> Vips::at_least_libvips? 8, 11
=> false
```

**Comment by vi-solutions** [comment]
@jcupitt I would try to test this but I can't enter a rails console as the image_processing gem fails during startup. What do I do about ruby-vips picking the wrong version?

**Comment by jcupitt** [comment]
It depends how you installed your new libvips, what platform you are using, and how you are managing your deployment. You probably need to set a few environment variables somewhere.

**Comment by vi-solutions** [comment]
I'm running Ubuntu 18.04 installed from source from the libvips guide https://github.com/libvips/libvips/wiki/Build-for-Ubuntu. 
Been digging to see where exactly `vips_version` comes from. Pulling it directly from the libvips library?

**Comment by jcupitt** [comment]
Yes, it uses ruby-ffi to call into the libvips that it's linked to and retrieves the version string.

You probably need to add `/usr/local/lib` to `LD_LIBRARY_PATH` in the thing that launches your web server. Or perhaps just running `ldconfig` would do it, depending on your setup.

**Comment by vi-solutions** [comment]
@jcupitt Yes LD_LIBRARY_PATH did the trick THANK YOU THANK YOU!!

**Comment by jcupitt** [comment]
\o/
