### ISSUE TITLE
Memory usage increases over time

### ISSUE THREAD

**Issue by aglushkov** [libvips/ruby-vips#225]
### Brief Description
I found this when my server runs out of memory  when I uploaded an image.

### System 
vips-8.9.1-Tue Jan 28 13:05:46 UTC 2020
ruby 2.6.5p114

### Simplest self-contained example code to demonstrate issue
This example shows memory usage increases after each image processing.
It compares libvips with imagemagick, so we can see image magick memory consumption remains same, and vips grows.
To execute it, save it to file 'benchmark.rb' and run `ruby benchmark.rb`
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| 'https://github.com/#{repo}.git' }

  gem 'down'
  gem 'image_processing'
end

require 'down'
require 'image_processing'
require 'mini_magick'
require 'ruby-vips'

# https://stackoverflow.com/questions/7220896/get-current-ruby-process-memory-usage/7863068#7863068
def current_process_memsize
  _pid, size = `ps ax -o pid,rss | grep -E "^[[:space:]]*#{$$}"`.strip.split
  "#{size.to_i / 1024.0} MB"
end

# 1500x1500 image
tempfile = Down.download("https://robohash.org/YOUR-TEXT.png?size=1500x1500")

puts '----'
puts "Initial Memory: #{current_process_memsize}"

puts '----'
puts 'ImageMagick processing:'
20.times do |step|
  ImageProcessing::MiniMagick.source(tempfile).resize_to_limit!(400, 400)
  puts current_process_memsize
end

puts '----'
puts 'Vips processing:'
20.times do |step|
  ImageProcessing::Vips.source(tempfile).resize_to_limit!(400, 400)
  puts current_process_memsize
end
# ----
# Initial Memory: 175.609375 MB
# ----
# ImageMagick processing:
# 175.609375 MB
# 175.609375 MB
# 175.609375 MB
# 175.609375 MB
# 175.609375 MB
# 175.609375 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# 178.33203125 MB
# ----
# Vips processing:
# 223.86328125 MB
# 250.4921875 MB
# 278.70703125 MB
# 295.34765625 MB
# 308.0703125 MB
# 330.5859375 MB
# 340.62890625 MB
# 350.2890625 MB
# 358.74609375 MB
# 369.328125 MB
# 380.78515625 MB
# 382.890625 MB
# 385.5546875 MB
# 393.7890625 MB
# 395.0234375 MB
# 396.77734375 MB
# 399.16015625 MB
# 405.359375 MB
# 417.671875 MB
# 417.671875 MB

**Comment by jcupitt** [comment]
Hello @aglushkov,

minimagick works by shelling out to the imagemagick executable, so no processing occurs in the Ruby process. This means that the ruby process size stays completely constant (but your `/tmp` area will be hammered, of course).

ruby-vips runs everything in the ruby process, so there are no temporary files, but of course you see memory fragmentation and GC activity instead.

I changed your program to be:

```ruby
puts 'Vips processing:'
2000.times do |step|
  ImageProcessing::Vips.source(tempfile).resize_to_limit!(400, 400)
  puts "#{step}: #{current_process_memsize}"
end
```

ie. run for 2,000 loops, and I see:

![x](https://user-images.githubusercontent.com/580843/77665696-ea3ed880-6f77-11ea-841f-9cc84ae129c0.png)

So the process stabilizes over time as memory fragments and settles down.

**Comment by jcupitt** [comment]
libvips keeps a cache of recenrtly executed operations. You can disable this for a drop in memory use:

```ruby
puts 'Vips processing:'
Vips::cache_set_max 0
2000.times do |step|
```

I see:

![x](https://user-images.githubusercontent.com/580843/77666742-3b030100-6f79-11ea-93bb-0d17e4d872ae.png)


ie. it stabilizes at about 400MB rather than 550MB.

**Comment by aglushkov** [comment]
@jcupitt Yes, its stabilizes, so it's probably not an issue for servers that have a lot of free memory.

Probably it should be documented somehow that this library (that is very light :1st_place_medal: ) will add additional 200-300 MB per process? For 2GB server with 2 rails servers and sidekiq it will use additionally 300MB * 3 = 900MB for example.

Is it possible maybe to add an option to use vips binary file directly as imagemagick does?

**Comment by jcupitt** [comment]
It depends on many factors -- 1500x1500 is quite small. Try with a cell phone-size jpg image, for example:

```
$ /usr/bin/time -f %M:%e convert nina.jpg -resize 400x400 x.jpg
214916:0.78
$ /usr/bin/time -f %M:%e vipsthumbnail nina.jpg --size 400x400 -o x.jpg
32936:0.27
```

Now minimagick will need much more memory than ruby-vips (though it depends how you configure it).

**Comment by aglushkov** [comment]
I found this memory bloat can be fixed with simple tips:

1) Disabling cache Vips.cache_set_max(0) (https://github.com/libvips/ruby-vips/issues/225#issuecomment-604508054) (I don't see any real execution speed changes with my benchmark)
2) Adding environment variable MALLOC_ARENA_MAX=2 [(why?)](https://www.joyfulbikeshedding.com/blog/2019-03-14-what-causes-ruby-memory-bloat.html), or compile ruby with jemalloc

I think this issues can be closed, but it would be great too see such tips to reduce memory in Readme or Wiki pages.

@jcupitt Thanks for great work on this library :+1:

**Comment by jcupitt** [comment]
I'm glad to hear you found a solution.

`Vips::cache_set_max(0)` is quite extreme -- I would perhaps try 10.

**Comment by matpowel** [comment]
@jcupitt I think this is causing a lot of memory issues on our worker processes on Heroku, it's a hunch at the moment so we'll add instrumentation but for now I'm a little confused about the cache_set_max method. It looks like it's attached through FFI so it calls out to the C lib, but setting it on the module like that makes it feel like it's a global setting. Will it apply to all future Vips calls across the entire process (assuming Vips is not reloaded)?

@aglushkov are you running within a Rails app? If so, did you disable the cache globally or for one particular operation?

**Comment by jcupitt** [comment]
Hi @matpowel, yes, it's a global setting for the process. Calling it will make the cache downsize on the next vips operation.

libvips 8.10 has a smaller default, so I'd be surprised if it made much difference now.

**Comment by matpowel** [comment]
@jcupitt I assume you mean the next vips operation and all future vips operations in the same Ruby process? So in the context of a Rails process, this would mean every vips operation run until that process is restarted?

Basically we have a piece of code that we've identified that seems to be capable of increasing memory consumption by hundreds (600+)mb even though the largest image it would ever process is probably 10-15mb. Does that seem right? Code is below, we haven't added enough profiling yet to determine if it's the Vips processing or ActiveStorage somehow doing something weird..

```
    image = ImageProcessing::Vips.source(io)
                                 .resize_to_limit(1280, 1280)
                                 .convert('jpg')
                                 .saver(quality: 85)
                                 .call
    DocumentPage.create!(
      uploaded_document: self,
      page_number: page_number,
      file: { io: image, filename: "#{basename}.jpg" }
    )
```

**Comment by jcupitt** [comment]
@matpowel that sounds weird, you should see steady and low memory use, I'd think.

What's `io` in your example? Could you open a new issue with a complete, standalone program which shows the problem? The code at the top of this issue would be a good model.
