### ISSUE TITLE
Is it possible to "cut" out the center of an image?

### ISSUE THREAD

**Issue by brandoncc** [libvips/ruby-vips#228]
![border-preview](https://user-images.githubusercontent.com/543973/78407085-db2fda00-75b8-11ea-81c5-42f068d4a5be.png)

Is it possible to turn the center of this image into a transparent section? I can make the center any color as a template section, and I don't know what colors the border might consist of. The border image is user-provided.

Any pointers are appreciated.

**Comment by jcupitt** [comment]
Hello @brandoncc,

Sure, make a zero image (255 is solid, 0 is transparent) and insert it. Something like:

```
image = Vips::Image.new_from_file "input.png"
transp = Vips::Image.black 570, 570
image = image.insert transp, 21, 21
image.write_to_file "output.png"
```

**Comment by brandoncc** [comment]
@jcupitt thanks for that.

The tricky part is that the center is not a perfect square, it has round edges. Since I posted, I came up with a plan which involves a "template". Here is my new image, followed by the code I am attempting to use it in:

![image](https://user-images.githubusercontent.com/543973/78411811-e2111980-75c5-11ea-8f69-0f2d6781304e.png)

```
image = Vips::Image.pdfload_buffer(pdf.render, n: 2, background: [0, 0, 0, 0])

template = image.crop(0, 0, image.width, image.height / 2)
template.add_alpha unless template.has_alpha?

border_and_background = image.crop(0, image.height / 2, image.width, image.height / 2)
border_and_background.add_alpha unless border_and_background.has_alpha?

border_and_background
  .composite(template, :clear)
  .write_to_file(file_path, Q: 85)
```

Unfortunately, this results in a completely blank (transparent) image. My goal is for the center "templated" section to be transparent, but the outer border to be present from the other image.

Am I close? Thanks again!

**Comment by brandoncc** [comment]
By the way, difference actually comes close, but ends up with the center being black...

**Comment by brandoncc** [comment]
I minimized the code to:

```
image = Vips::Image.pdfload_buffer(pdf.render, n: 2)

template = image.crop(0, 0, image.width, image.height / 2)
border_and_background = image.crop(0, image.height / 2, image.width, image.height / 2)

border_and_background
  .composite(template, :clear)
  .write_to_file(file_path, Q: 85)
```

The result is the same.

**Comment by brandoncc** [comment]
If you find it helpful, here is the image that is stored in `image`.

![image](https://user-images.githubusercontent.com/543973/78414893-44244b80-75d3-11ea-9ac8-210123730bbb.png)

**Comment by jcupitt** [comment]
You could draw the rounded rect with SVG, that's a simple fix:

```ruby
#!/usr/bin/ruby

require 'vips'

margin = 100
radius = 50
image = Vips::Image.new_from_file ARGV[0], access: :sequential

rect_width = image.width - 2 * margin
rect_height = image.height - 2 * margin
rect = Vips::Image.new_from_buffer %(
  <svg viewBox="0 0 #{image.width} #{image.height}">
    <rect rx="#{radius}" ry="#{radius}" 
     x="#{margin}" y="#{margin}" 
     width="#{image.width - 2 * margin}" height="#{image.height - 2 * margin}" 
     fill="#fff"/>
  </svg>
), ""

# the alpha of the rect is transparent at the edges, but solid in the centre --
# we want the opposite of that
image = image.bandjoin rect[3].invert

image.write_to_file ARGV[1]
```

It'll be a bit slow for large images. To draw a big rect with round corners, I'd make a circle, cut into four, insert those into the four corners of a large black square, then insert that into a huge white square, then finally use that as the alpha. That should run very quickly.

**Comment by jcupitt** [comment]
Oh, that assumes your input image has no alpha, of course.

**Comment by brandoncc** [comment]
Thanks @jcupitt, unfortunately that would be a very last resort solution given how I need to use it. Does that mean I can't "cut out" a section using compositing like I thought I could?

**Comment by brandoncc** [comment]
I figured out how to do it in imagemagick:

```
convert image.jpg template.jpg -alpha Off -compose CopyOpacity -composite border_preview.png
```

I got that from [here](https://www.imagemagick.org/Usage/masking/#editing). It works, but I would rather use vips if possible.

Here is the result of the `convert` call:

![border_preview](https://user-images.githubusercontent.com/543973/78422754-976bbd80-7616-11ea-8b48-5290fd27bb37.png)

**Comment by jcupitt** [comment]
That imagemagick line is doing exactly what my ruby did, I think. It's removing the alpha from the border and replacing it with `template.jpg` (except I was rendering the template with svg).

**Comment by brandoncc** [comment]
It is very important that I don't create the mask in vips, though. It sounds like what I want is simply not possible (I need everything that command does, including using the mask from an image), so I guess I will have to use imagemagick for this one.

Thank you for trying, I really appreciate it.

**Comment by jcupitt** [comment]
You can do it, I was just making the transparent bit with svg instead of having it pre-drawn. For example:

```ruby
#!/usr/bin/ruby
  
require 'vips'

image = Vips::Image.new_from_file ARGV[0]

template = image.crop 0, 0, image.width, image.height / 2
border_and_background = image.crop 0, image.height / 2, 
  image.width, image.height / 2

# take the alpha from the template ... we need to invert it to get transparent
# in the centre and solid at the edges
alpha = template[3].invert

# take RGB from the the border
rgb = border_and_background[0..2]

rgb.bandjoin(alpha).write_to_file ARGV[1]
```

**Comment by brandoncc** [comment]
Thank you!! This is exactly what I needed. It looks like the composition method I needed was `#bandjoin`.

You are a wizard, and your library continues to be amazing. Thanks again.
