### ISSUE TITLE
Support for loading fontfiles from buffer/stream?

### ISSUE THREAD

**Issue by AdamT213** [libvips/ruby-vips#233]
I have many fontfiles stored in an s3 bucket. Currently I write them to a temp file, then read them, something like this: 

`res = s3.get_object(bucket: 'bucket', key: 'key', response_target: "#{Dir.tmpdir()}/#{font}.ttf")`
`text = Vips::Image.text("some text", {fontfile: "#{Dir.tmpdir()}/#{font}.ttf", font: font_name})`

This seems to have a significant impact on the performance of the whole processing operation, compared to just loading images, which can be done without writing to disk. Is there a similar way to load fontfiles? I don't assume that a stream would help much, since unlike images, I imagine the font files must be read entirely before the fonts can be applied, but how about reading from a buffer? If this is not supported, would it be possible to add? As far as I can tell from the source, it seems like the Image::text method comes directly from libvips, but perhaps I am missing something.

**Comment by jcupitt** [comment]
Hell @AdamT213, 

I doubt if loading via the filesystem is adding much overhead, I think it's more likely to be that text rendering itself is rather slow.

You could try benchmarking rendering with one of the standard fonts vs. with your custom font and see if there's a significant difference. Alternatively, perhaps you could pre-render and reuse some of the text?

**Comment by AdamT213** [comment]
Here is the result of 500 executions with a standard sans font vs one dowloaded from the web:

[#<Benchmark::Tms:0x00007fab1f49ef90
  @cstime=0.0,
  @cutime=0.0,
  @label="custom",
  @real=127.32764099998167,
  @stime=16.976691,
  @total=82.489236,
  @utime=65.512545>,
 #<Benchmark::Tms:0x00007fab1f4c5bb8
  @cstime=0.0,
  @cutime=0.0,
  @label="standard",
  @real=115.54594199999701,
  @stime=15.262639,
  @total=77.103569,
  @utime=61.84093>]

I suppose you are right, an extra 12 seconds over 500 executions isn't too significant I suppose, and there is bound to be some overhead just dowloading from Amazon anyway. Thanks!
