### ISSUE TITLE
How do I set draw_circle color?

### ISSUE THREAD

**Issue by Nakilon** [libvips/ruby-vips#234]
Seems like when I previously used this drawing primitive I used only `0` and `1` color values , but now I need more colors:

    image.draw_circle color, x, y, 2, fill: true

I was setting `color` to `[1, 1, 1]`, `[1, 0, 0]`, `[1, 0, 0]`, `[0, 1, 0]`, etc., but all circles are black.

![temp](https://user-images.githubusercontent.com/2870363/80225595-f2139a80-8653-11ea-8568-e40a89e0650e.png)

**Comment by Nakilon** [comment]
Nevermind. Have to use range `0..255`, like `[255, 255, 0]`.

![temp](https://user-images.githubusercontent.com/2870363/80225815-46b71580-8654-11ea-939f-b1257a7cca25.png)

**Comment by jcupitt** [comment]
Yes, they are just the pixel values to write to the file. You'll need 65535 for white in a 16-bit image, for example.
