### ISSUE TITLE
Alteration on read?

### ISSUE THREAD

**Issue by elcuervo** [libvips/ruby-vips#238]
Hi.
First I have to say that I love this project and the results so far has been amazing.

My question started when I implemented a perceptual hash for some tests and I notice that on the version I had at the moment (8.4 from stock ubuntu 18.04) I ended up with a different hash from the latest version I'm using in production (8.9.2).

Right now the only thing I can pin point is that there's a very subtle difference between the file read on both versions.

I'm still trying to understand when the difference happens but testing this:

```ruby
require "vips"

bytes = open(ARGV[0]).read
img = Vips::Image.new_from_buffer(bytes, "")
img.write_to_file "out.jpg"
```

I notice that the resulting file is not the same as the source material.

Is there any flags I'm missing to prevent modification? interpretation? something?

Thank you so much for your time.

**Comment by jcupitt** [comment]
Hello @elcuervo,

Could your jpg library have changed? Different versions of libjpeg can give very slightly different results. Your example code will almost certainly produce a different file -- if you decode and recode a JPG, you'll usually get a different image.

Formats like PNG should be more consistent, though you can still get differences in some circumstances.

**Comment by elcuervo** [comment]
@jcupitt thank you for the quick answer.

I haven't considered a different libjpg. I'll do some tests.

AFAIK the only change was the switch from stock to compile latest and greatest but there's a case for that difference.

Given the up-to-date quality of libvips I'm currently taking the results as "modern" so I'll keep checking them.

I have to implement the same ish thing in Go so if I find any substantial differences I'll reopen the issue.

Thanks!

**Comment by jcupitt** [comment]
The big one is libjpeg and libjpeg-turbo. They will give very slightly different results.

**Comment by elcuervo** [comment]
That should be the case I'm facing then ^_^ because the resulting difference I have (after hashing) is way to subtle 

```diff
- a2ca9535c6a669da
+ a2ca9535c6a269da
```

**Comment by elcuervo** [comment]
For the record:
You were absolutely correct.

Thank you again

**Comment by Nakilon** [comment]
I wonder what is your hashing algorithm )
