### ISSUE TITLE
VIPS 7.30 support?

### ISSUE THREAD

**Issue by eltiare** [libvips/ruby-vips#24]
Get this error attempting to install the ruby-vips gem on OS X:

extconf.rb:27:in `<main>': no pkg_config for any of following libvips versions: 7.29, 7.28, 7.27, 7.26, 7.24, 7.23, 7.22, 7.20 (RuntimeError)

I'm using 7.30. I've also installed 7.30 on Debian (in /usr/local with the system version still in place) and the updated version seems to work fine with ruby-vips.

**Comment by foresmac** [comment]
@stanislaw I just installed vips via the latest homebrew formula and it didn't link libxml-2.0 on OS X 10.10.2.

```bash
# pkg-config --cflags vips
Package libxml-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libxml-2.0', required by 'vips', not found
exit status 1
```

**Comment by foresmac** [comment]
And, just linking libxml2 looks like it could be problematic...

```
Violet:~ > brew link libxml2
Warning: libxml2 is keg-only and must be linked with --force
Note that doing so can interfere with building software.
```

**Comment by jcupitt** [comment]
Hi, it works for me, but you do need to fiddle with your `PKG_CONFIG_PATH`. Don't use the homebrew `libxml2.pc`, find the Apple one and add that directory to your search path.

**Comment by foresmac** [comment]
I linked the home-brew version and it worked. But I can unlink and fiddle with `PKG_CONFIG_PATH`.

**Comment by jcupitt** [comment]
I checked and I have:

```bash
$ echo $PKG_CONFIG_PATH 
/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/opt/X11/lib/pkgconfig
```

it all seems to work for me.
