### ISSUE TITLE
The :over blending mode does not work like I thought it should work after reading docs

### ISSUE THREAD

**Issue by Nakilon** [libvips/ruby-vips#240]
There is such approach to visualize two images that represent layers of some built structure -- putting them on top of each other with different hue:

![image](https://user-images.githubusercontent.com/2870363/85203134-351c8200-b314-11ea-9f3d-6c999b24c134.png)

There is also a source image that has two layers splitted:

![image](https://user-images.githubusercontent.com/2870363/85203149-4ebdc980-b314-11ea-9284-1c9a8a8d0f6e.png)

so I want to mix them to make it look like in previous image.

The `Blending` docs said that the `:over` mode means:

> the image shows what you would expect if you held two semi-transparent slides on top of each other

and I thought it's exactly what I need but when I did:

```ruby
a = image.crop(420, 45, 360, 550)
b = image.crop(20, 45, 360, 550)
a.composite2(b, :over).write_to_file "temp.png"
```

it just returned one of images not blending them at all. Seems like this blending mode needs an alpha layer to work as stated in docs and this layer should equal to 0.5:

```ruby
(a.add_alpha * [1,1,1,0.5]).composite2(
 b.add_alpha * [1,1,1,0.5], :over).write_to_file "temp.png"
```

![image](https://user-images.githubusercontent.com/2870363/85203274-45812c80-b315-11ea-87a7-aa1c08268789.png)

Then I tried other modes and made darker colors all black.
```ruby
        ((a - 51) * 1.25 * [0.7, 0.8, 0.7]).add_alpha.composite2(
        ((b - 51) * 1.25 * [0.7, 0.7, 0.8]).add_alpha, :lighten)
```

![image](https://user-images.githubusercontent.com/2870363/85203251-15d22480-b315-11ea-9d3b-1c6379f44a0e.png)

This seems to be what I need. I'm only not sure that ` - 51) * 1.25` is the correct way to do this in vips, maybe there is some method to move ends of curve without calculating these numbers.

**Comment by jcupitt** [comment]
Hi @Nakilon,

Yes, `composite` implements the PDF blending operations, so it needs an alpha. Images like JPGs are solid, so you'll need to add some kind of transparency layer if you want to compose them.

I think your problem is simpler though -- you just want to tint the monochrome images, then sum them. I would try something like:

```
#!/usr/bin/ruby

require 'vips'

map = Vips::Image.new_from_file "map.jpg"
top = map.crop(20, 45, 360, 550)
bottom = map.crop(420, 45, 360, 550)

# give an image a tint 
module Vips
  class Image
    def tint(colour)
      (self.colourspace(:b_w) * colour).copy(interpretation: :srgb)
    end
  end
end

# make the images monochrome, then give them a tint
top = top.tint [0.7, 0.5, 0.5]
bottom = bottom.tint [0.5, 0.5, 0.7]

# and sum to make the overlay
result = top + bottom

result.write_to_file "out.jpg"
```

To make:

![out](https://user-images.githubusercontent.com/580843/85203766-d18c5780-b307-11ea-9129-53ce020c8d10.jpg)

**Comment by jcupitt** [comment]
I suppose another technique would be to use the mono version of the two maps as the alpha, and have the RGB bands as solid colour.

```ruby
#!/usr/bin/ruby

require 'vips'

map = Vips::Image.new_from_file "map.jpg"
top = map.crop(20, 45, 360, 550)
bottom = map.crop(420, 45, 360, 550)

module Vips
  class Image
    def tint(colour)
      new_from_image(colour).bandjoin(colourspace(:b_w)[0])
    end
  end
end

top = top.tint [200, 100, 100]
bottom = bottom.tint [100, 100, 200]

result = top.composite(bottom, :over)

result.write_to_file "out.jpg"
```

To make:

![out](https://user-images.githubusercontent.com/580843/85203946-f0d7b480-b308-11ea-8de5-4af7e2cdd2f3.jpg)

Which maybe looks a little more natural.

**Comment by Nakilon** [comment]
The first one makes overlapping too bright. The second one looks cool!

**Comment by Nakilon** [comment]
For some reason you last code produces:

![image](https://user-images.githubusercontent.com/2870363/85205793-41a9d600-b326-11ea-8ae6-79d060a63e6c.png)

**Comment by Nakilon** [comment]
Oh, nevermind. This is how macOS shows semitransparent images. `.flatten` did the trick.
