### ISSUE TITLE
Strip everything but the color space

### ISSUE THREAD

**Issue by wilg** [libvips/ruby-vips#248]
I'm using ruby-vips via ActiveStorage, and I need to strip the metadata off my images, which I am doing like so:

```rb
img.variant(convert: :jpg, resize_to_fill: [256, 256], saver: {strip: true})
```

However, I would like to keep the color space, as stripping it reduces the quality of images from devices like the iPhone, which use P3 color space.

Any ideas for how to do this?

**Comment by jcupitt** [comment]
Hello @wilg,

There isn't a one-liner, but you can just remove all metadata except the profile before calling save.

For example:

```ruby
#!/usr/bin/ruby

require 'vips'

image = Vips::Image.new_from_file ARGV[0], access: :sequential

# libvips images are all immutable and are shared between threads, so before we
# modify the image metadata, we must make a private copy of the image
#
# this will just copy some pointers and is very quick

image = image.copy
image.get_fields.each do |field|
  image.remove field unless field == "icc-profile-data"
end

image.write_to_file ARGV[1]
```

I can run like this:

```
$ ./strip.rb ~/pics/wtc.jpg x.jpg
$ vipsheader -a x.jpg 
x.jpg: 9372x9372 uchar, 3 bands, srgb, jpegload
width: 9372
height: 9372
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: x.jpg
vips-loader: jpegload
jpeg-multiscan: 0
jpeg-chroma-subsample: 4:2:0
exif-data: 186 bytes of binary data
resolution-unit: in
exif-ifd0-Orientation: 1 (Top-left, Short, 1 components, 2 bytes)
exif-ifd0-XResolution: 25400/1000 (25.400, Rational, 1 components, 8 bytes)
exif-ifd0-YResolution: 25400/1000 (25.400, Rational, 1 components, 8 bytes)
exif-ifd0-ResolutionUnit: 2 (Inch, Short, 1 components, 2 bytes)
exif-ifd0-YCbCrPositioning: 1 (Centred, Short, 1 components, 2 bytes)
exif-ifd2-ExifVersion: Exif Version 2.1 (Exif Version 2.1, Undefined, 4 components, 4 bytes)
exif-ifd2-ComponentsConfiguration: Y Cb Cr - (Y Cb Cr -, Undefined, 4 components, 4 bytes)
exif-ifd2-FlashPixVersion: FlashPix Version 1.0 (FlashPix Version 1.0, Undefined, 4 components, 4 bytes)
exif-ifd2-ColorSpace: 65535 (Internal error (unknown value 65535), Short, 1 components, 2 bytes)
exif-ifd2-PixelXDimension: 9372 (9372, Long, 1 components, 4 bytes)
exif-ifd2-PixelYDimension: 9372 (9372, Long, 1 components, 4 bytes)
orientation: 1
icc-profile-data: 3144 bytes of binary data
```

You can see image still has 186 bytes of EXIF. This is because an EXIF block is required by the JPG spec, so if it's asked to save a JPG file with no EXIF, the saver will add a minimal set.

**Comment by wilg** [comment]
Thanks, that was super helpful. I think I got it working.

For anyone else who might be trying to make this work with ActiveStorage, here's how I integrated it:

```ruby
img.variant(convert: :jpg, resize_to_limit: [1125, 1125 * 2], strip_everything_but_profile: true)

# monkey patch image_processing in an initializer
# you can't just use a `custom` proc in the `variant` because ActiveStorage can't serialize it
module VipsProcessorPatch
  def strip_everything_but_profile
    image.get_fields.each do |field|
      image.remove field unless field == "icc-profile-data"
    end
    image
  end
end

ImageProcessing::Vips::Processor.include VipsProcessorPatch
```

**Comment by jcupitt** [comment]
Oh, nice! But you **must** do the `copy`. You will get unpredictable behaviour if you don't.

**Comment by wilg** [comment]
I had issues with the copy always returning `nil` and assumed that `ImageProcessing::Vips::Processor` was handling it, since the other methods I looked at (I think) didn't use `copy`.

**Comment by jcupitt** [comment]
That's odd -- `copy` should succeed or raise an exception. Perhaps it's been rebound to something else? Is 'image' a real ruby-vips image, or has it been modified by `image_processing`?

You need the copy before you modify image metadata. libvips images are immutable and are shared behind your back: if two images are made in the same way (the same sequence of operations has made them), then they will be the same underlying object. Two quite different parts of your program with no direct relationship can be using the same C object.

If one part of your program removes a metadata field, it'll vanish for the other part too, and you'll get races and even a crash. `copy` is a special operation in that (as well as copying) it creates a unique (unshared) object. After copy, you can call remove safely.

**Comment by wilg** [comment]
Makes sense, I'll dig in. Is there a way the `ruby-vips` API could enforce the immutability so its not possible to make such an error?

**Comment by jcupitt** [comment]
We experimented with a few ideas, but none of the solutions we tried for metadata worked 100%.

There was a related issue --- how to improve the speed of the destructive draw operations: https://github.com/libvips/ruby-vips/issues/139

Something like this:

```ruby
modified_image = start_image.destructive do |x|
    x.draw_line! 255, 10, 10, 100, 100
    x.draw_line! 255, 10, 110, 100, -100
end
```

The `destructive` method does a copy, then the `draw_line!` operations work destructively on the unshared image, then that's returned  to `modified_image`. 

There's a branch which implements this, but it's a bit unfinished. You'd need some kind of mechanism which only allowed `draw_line!` inside a destructive block. It would need to handle nested destructive blocks as well. You could modify metadata inside one of these things too.

I don'#t know if you have any thoughts on implementing this, or making it prettier?

**Comment by wilg** [comment]
That seems like a decent solution. Here's a tweaked API for no real reason:

```ruby
new_image = image.mutate do |img|
    img.draw_line! 255, 10, 10, 100, 100
    img.draw_line! 255, 10, 110, 100, -100
end
```

Not fully versed in this package's implementation, perhaps you could simply have `mutate` set some private instance vars to guard against inappropriate mutations, something like this:

```ruby
def mutate
   img = copy
   img.instance_variable_set(:@mutable, true)
   yield img
   img.instance_variable_set(:@mutable, false)
   img
end

# Mutating methods
def draw_line!(*args)
   unless @mutable
     raise ImmutableError.new("Image is not mutable, for thread-safety `draw_line!` can only be called inside a `mutate` block.")
   end
   # ...
end
```

**Comment by wilg** [comment]
And I think maybe you could handle nested blocks just by having special behavior (maybe just don't copy?) if `@mutable == true` already.

**Comment by jcupitt** [comment]
That looks nicer.

Thinking again, you could also make a new `MutableImage` class:

```ruby
  class MutableImage < Vips::Object
    def draw_line! ink x1, y1, x2, y2
    end
    def set! field, value
    end
    def remove! field
    end
    etc.
  end
```

And remove those methods from `Image`.

The `mutate` method could be on `Image` and would do a copy, make a `MutableImage`, and yield that to the block.

**Comment by jcupitt** [comment]
So your remove everything but the profile might be:

```ruby
  def strip_everything_but_profile
    image.mutate do |x|
      image.get_fields().each do |field|
        x.remove! field unless field == "icc-profile-data"
      end
    end
  end
```

**Comment by jcupitt** [comment]
Sorry to keep pinging this issue.

We'd need to keep the set and remove methods on Image to avoid an API break, but perhaps they could just print warning messages pointing people at the new `mutate` method. Is that how these things are usually handled?

**Comment by wilg** [comment]
The subclass implementation would end up as a breaking API change though, which could be an issue.

I'd say the easiest way for making the breaking change would be to introduce a small revision, like 2.0.19 that adds the mutate feature and prints a warning for existing users and says it will be an error in the next major version, and then in a 3.0 release make the warning an error or remove the methods entirely or whatever.

**Comment by jcupitt** [comment]
See https://github.com/libvips/ruby-vips/issues/139

**Comment by jcupitt** [comment]
(there's a possible implementation of `mutate` there)

**Comment by jcupitt** [comment]
I've merged that branch to master, so you can now write:

```
  def strip_everything_but_profile
    image.mutate do |x|
      image.get_fields().each do |field|
        x.remove! field unless field == "icc-profile-data"
      end
    end
  end
```

It'll be in 2.0.18.
