### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by ankane** [libvips/ruby-vips#262]
Hey @jcupitt, saw there was a version bump in 1e1d6f39755f2db5e2b1ccbf1200015ef136ed4d to 2.0.19, but it looks like 2.0.18+ was never released on RubyGems (also, some of the changes listed in the changelog for 2.0.18 were added after the release date).

Edit: RubyGems link - https://rubygems.org/gems/ruby-vips

**Comment by jcupitt** [comment]
Ooooop! Sorry @ankane, you're right. I've reverted the version bump.

I was sure I'd pushed that, I must be confused :(

We should probably push 2.0.18 out in a few days.

**Comment by ankane** [comment]
Great, thanks @jcupitt. Not sure if I'm reading it wrong, but the dates in the changelog don't seem to match up with RubyGems fwiw.

**Comment by jcupitt** [comment]
The date is when work on that version starts (perhaps not very useful).

**Comment by ankane** [comment]
Ah, gotcha. I think it's more common to use the release date.
