### ISSUE TITLE
is there a way to load files from blob data?

### ISSUE THREAD

**Issue by orlando** [libvips/ruby-vips#27]
like the `from_blob` method from Rmagick

sorry for posting this question as an issue... also, is there any google group for this gem? thanks

**Comment by ryankopf** [comment]
Just want to leave a comment for anyone searching for "to_blob" for OUTPUT, you'll want something like jpegsave_buffer

**Comment by jcupitt** [comment]
The ruby-vips 2 API is:

```ruby
image = Vips::Image.new_from_buffer(some_binary_data, "")
some_binary_data = image.write_to_buffer(".jpg")
```

Documented here:

https://www.rubydoc.info/gems/ruby-vips/Vips/Image#new_from_buffer-class_method

https://www.rubydoc.info/gems/ruby-vips/Vips/Image#write_to_buffer-instance_method

You can also load and save to arrays, C-style blocks of memory, file descriptors (including pipes), URIs, etc. etc., see:

https://www.rubydoc.info/gems/ruby-vips/Vips

For a general discussion.

**Comment by Nakilon** [comment]
Since this ticket got necroed.

> is there any google group

I would ask if @jcupitt has considered the new Github "Discussion" tab.

**Comment by jcupitt** [comment]
Sure, let's try it out for a bit. I've not used it before.

https://github.com/libvips/ruby-vips/discussions
