### ISSUE TITLE
Docs say Vips::Interpolate.new wants a Symbol but it wants a String

### ISSUE THREAD

**Issue by Nakilon** [libvips/ruby-vips#277]
When I google ruby-vips docs it usualy leads me to this website: https://www.rubydoc.info/gems/ruby-vips

The example there says the `Vips::Interpolate.new` accepts a Symbol.
Then in the code I've found this too -- the example with a Symbol: https://github.com/libvips/ruby-vips/blob/63316346e56f426b6e4e14bfc3d0d8d07c02c030/lib/vips/interpolate.rb#L28

But it throws `TypeError: no implicit conversion of Symbol into String` when I do:

```ruby
 im2c.resize(10, interpolate: Vips::Interpolate.new(:nearest))
```

I remember there was already some symbol-string related mismatch and a fix a year ago but I don't remember where.

`gem update ruby-vips` says it is the latest.

I'm sorry for ignoring the bug report template.

UPD: oh, I actually wanted `Image#resize` `:kernel` arg, not `:interpolate` and maybe that's where it was fixed previous time.

**Comment by jcupitt** [comment]
Hi @Nakilon I just pushed 2.1 with a fix for this (I think).

There's a useful new `mutate` feature too:

https://libvips.github.io/libvips/2021/03/08/ruby-vips-mutate.html
