### ISSUE TITLE
Warnings from ::Vips::Image.new_from_array

### ISSUE THREAD

**Issue by doits** [libvips/ruby-vips#291]
After upgrade to ruby-vips 2.1.0 I get the following warnings **on ubuntu focal** with **vips 8.9.1**:

```rb
# test.rb

require "vips"

::Vips::Image.new_from_array [[-1, -1, -1],
                              [-1, 32, -1],
                              [-1, -1, -1]], 24
```

Output:

```
(test.rb:40847): VIPS-WARNING **: 11:21:01.732: can't set metadata "scale" on shared image

(test.rb:40847): VIPS-WARNING **: 11:21:01.732: can't set metadata "offset" on shared image
```

**To Reproduce**

Use the following bash script on an **ubuntu focal** machine:

```bash
# install libvips if not installed
apt install libvips42

# create Gemfile
echo "source 'https://rubygems.org'
gem 'ruby-vips'" > Gemfile

# install gems
bundle install

# create test file
echo 'require "vips"

::Vips::Image.new_from_array [[-1, -1, -1],
                              [-1, 32, -1],
                              [-1, -1, -1]], 24' > test.rb

# run test file
bundle exec ruby test.rb
```

**Expected behavior**

No warnings

**Environment**
 - OS: Ubuntu Focal
 - Version 20.04.2
 - Vips version: libvips42:amd64/focal 8.9.1-2 uptodate
 - Gemfile.lock

   ```
    GEM
      remote: https://rubygems.org/
      specs:
        ffi (1.15.0)
        ruby-vips (2.1.0)
          ffi (~> 1.12)

    PLATFORMS
      x86_64-linux

    DEPENDENCIES
      ruby-vips

    BUNDLED WITH
       2.2.7
   ```

**Additional context**

I thought it was an issue with the image processing gem so I opened an issue there, too: https://github.com/janko/image_processing/issues/83

I also have some image corruption after the upgrade to `ruby-vips 2.1.0`, but it only happens on my ubuntu focal server and not locally on my mac os development machine (which has a more recent vips version). Maybe the warnings are the cause.

**Comment by jcupitt** [comment]
Hi Markus, thanks for the detailed report.

Yes, this is ruby-vips 2.1 needing a more recent libvips.

For now, I'd go back to an earlier ruby-vips. I'll see if I can update ruby-vips 2.1 to work with libvips 8.9.1.

Sorry about this :(

**Comment by doits** [comment]
Thanks for the information. Just a note: It happens with the latest ubuntu LTS, so it probably happens for others, too.

If there is no (easy) fix I think ruby-vips should raise an error if an old version of vips is detected, so at least users know to downgrade ruby-vips or upgrade vips (if possible).

Is it `mutate` that does not work correctly so even other things than `::Vips::Image.new_from_array` are broken, too?

**Comment by jcupitt** [comment]
libvips 8.9.0 and 8.9.1 had a horrible misfeature that blocked metadata changes unless refcount was 1.

This was a really bad idea and 8.9.2 (I think) changed it. Anyway, it prevents ruby-vips from modifying metadata, even when using `mutate`. I might be able to work around it, I'm not sure.

**Comment by doits** [comment]
Alright, thanks. It works correctly with `ruby-vips 2.0.17` and `vips 8.9.1` though, so in the meantime this is the easiest solution to keep it running.

**Comment by shreyas-sriram** [comment]
Any update on this issue?

**Comment by jcupitt** [comment]
I've made a PR that tries to work around this problem. Would anyone be able to test it? 

It's extremely ugly, so confirmation that it at least sort-of works from someone else would be reassuring :( 

I've run the ruby-vips test suite with libvips 8.8, 8.9, 8.10 and 8.11, and tried @doits test program:

```ruby
#!/usr/bin/ruby

require "vips"

::Vips::Image.new_from_array [[-1, -1, -1],
                              [-1, 32, -1],
                              [-1, -1, -1]], 24
```

**Comment by shreyas-sriram** [comment]
@benubois With respect to https://github.com/janko/image_processing/issues/84, does this solve the issue? I am using [jekyll_image_processing](https://github.com/benubois/jekyll_image_processing) and blocked due to this.

**Comment by benubois** [comment]
@shreyas-sriram I re-ran [my example](https://github.com/janko/image_processing/issues/84) with the `fix-mutate-with-libvips8.9.1` branch and it did not trigger the issue I saw before.

Thanks @jcupitt!

**Comment by jcupitt** [comment]
Great! Thanks for testing!

I've merged to master, updated the autodocs, and pushed to rubygems as ruby-vips 2.1.1
