### ISSUE TITLE
Vips::Image.new_from_memory does not accept FFI::Pointer

### ISSUE THREAD

**Issue by sled** [libvips/ruby-vips#295]
**Describe the bug**
The documentation states that `Vips::Image.new_from_memory` should accept a `FFI::Pointer` as data argument, but a `FFI::Pointer` does not meet the requested interface because it's missing a `bytesize` method, which a `String` does have.

This also affects `Vips::Image.new_from_memory_copy` 

Link to documentation: https://www.rubydoc.info/gems/ruby-vips/Vips%2FImage.new_from_memory

The incompatibility seems to have been introduced with this commit: https://github.com/libvips/ruby-vips/commit/a7eef4c59abdef607df7aeee12018871af83c2e4

**To Reproduce**
```
ptr = FFI::MemoryPointer.new(:uchar, 10*10*3)
=> #<FFI::MemoryPointer address=0x00007fc2317b3ed0 size=300>
Vips::Image.new_from_memory(ptr, 10, 10, 3, :uchar)
=> Traceback (most recent call last):
        3: from bin/console:14:in `<main>'
        2: from (irb):16
        1: from /ruby/2.7.2/lib/ruby/gems/2.7.0/gems/ruby-vips-2.1.0/lib/vips/image.rb:343:in `new_from_memory'
NoMethodError (undefined method `bytesize' for #<FFI::MemoryPointer address=0x00007fc2317b3ed0 size=300>)
Did you mean?  type_size
```

**Expected behavior**
It is expected to load a `Vips::Image` from a `String` or `FFI::Pointer`.

**Comment by jcupitt** [comment]
Hi @sled,

You're right, this seems to be broken. It needs length, so I suppose it should ask for `String` or subclass of `AbstractMemory` and use `#size`. Would that fix your problem?

**Comment by sled** [comment]
Hey @jcupitt 

thanks for the quick reply. I guess it's a bit more complicated, FFI's inheritance is as follows:

`FFI::MemoryPointer < FFI::Pointer < FFI::AbstractMemory`

`FFI::MemoryPointer` usually knows the size of the chunk of memory it points to because it was allocated via FFI in Ruby, but `FFI::Pointer` may not because it could just be an address to a chunk of memory allocated by an external library. 

In my case I'm generating a DataMatrix (similar to QR codes) using the DMTX C-library which returns an `FFI::Pointer` which is only an address without size information, because the memory is allocated in the external DMTX C-Library e.g. the function call to the library returns a `#<FFI::Pointer address=0x00007fc233104000>`

Calling `.size` on that pointer yields `9223372036854775807` which is the constant `LONG_MAX` (see https://github.com/ffi/ffi/blob/a7f4c951f5004c338fbae237bbae69fbb6ca66c6/lib/ffi/abstract_memory.rb)

The same can be reproduced with a pointer pointing to an arbitrary address in memory: 

```
irb(main):045:0> FFI::Pointer.new(1).size
=> 9223372036854775807
irb(main):047:0> FFI::Pointer.new(1).size_limit?
=> false
```

However if I cast a `FFI::MemoryPointer` to `FFI::Pointer` it knows about it's size:

```
irb(main):048:0> memory_ptr = FFI::MemoryPointer.new(:uchar, 10*10*3)
=> #<FFI::MemoryPointer address=0x00007fc236db31d0 size=300>
irb(main):049:0> ptr = FFI::Pointer.new(memory_ptr)
=> #<FFI::Pointer address=0x00007fc236db31d0 size=30>
irb(main):050:0> ptr.size
=> 300
irb(main):051:0> ptr.size_limit?
=> true
```

The benefit of accepting an `FFI::Pointer` is, that it would be possibly to directly manipulate the output of another external library without copying.

There's a way however to cast an `FFI::Pointer` to another `FFI::Pointer` aware of the memory size it points to using the `slice` method (see https://www.rubydoc.info/github/ffi/ffi/FFI%2FPointer:slice):

```
WIDTH = 80
HEIGHT = 80
BYTES_PER_PIXEL = 3

ptr = call_to_external_c_library(WIDTH, HEIGHT) # => #<FFI::Pointer address=0x00007f9780813a00>
ptr.size # => 9223372036854775807
ptr.size_limit? # => false

ptr_slice = ptr.slice(0, WIDTH*HEIGHT*BYTES_PER_PIXEL) # => #<FFI::Pointer address=0x00007f9780813a00 size=19200>
ptr_slice.size # => 19200
ptr_slice.size_limit? # => true
```

**Possible solutions**

1) Calculate the expected size using the `width`, `height`, `bands` and `format` parameters. Might be brittle?
2) Require the `size_limit?` to return true if a `FFI::AbstractMemory` is passed, throw an error if size is unknown.
3) Add another, optional, argument, specifying the size of the data in bytes, could be optional if:
       - `data` responds to bytesize in case of strings
       - `data` is a `FFI::AbstractMemory` with `.size_limit?` returning true so we can use `.size`

**Comment by jcupitt** [comment]
Thanks for the thoughtful notes. It's a while since I looked at this :(

I don't like computing the expected size, it'd make it extremely easy to segv. And everywhere else in libvips we pass a size, so skipping the size here feels inconsistent.

How about your option 2.? As you say, you can rewrap your pointer and avoid the copy.

**Comment by sled** [comment]
Option 2 would also be my choice as it doesn't change the function signature.

I could prepare a PR for this change including specs, it would be helpful to know what should happen if a `FFI::Pointer` with unknown size is passed so the error behaviour is consistent with the rest of the library.

**Comment by jcupitt** [comment]
That would be great if you have time, thank you! I'd throw an exception with a message explaining the issue.

**Comment by jcupitt** [comment]
This is released now, I'll close.
