### ISSUE TITLE
pdfload: pages out of range Error

### ISSUE THREAD

**Issue by foxmerald** [libvips/ruby-vips#301]
When trying to process a PDF file that contains only one, but a quite huge page `vips_pdf_loader` throws `Vips::Error` `pdfload: pages out of range`. See this example file - it's huge, but a valid pdf: [upload.pdf](https://github.com/libvips/ruby-vips/files/6460549/upload.pdf).

There also seems a NullPointerError to be thrown related to the above mentioned `pdfload` error, see
`/vips/gvalue.rb:143:in 'write_bytes': invalid memory write at address=0x0000000000000000 (FFI::NullPointerError)`

We're currently using `ruby-vips-2.0.13`. What can be done to prevent this error?

**Comment by foxmerald** [comment]
I'm using `vips-8.9.2` and tried out the newest `ruby-vips 2.1.2`.

Your example code is working for me as well. But when using `vips_pdf_loader` in Paperclip's `has_attached_file` `processors`, the above error is thrown.

**Comment by jcupitt** [comment]
I tried in ruby as well, using vips-8.9 and ruby-vips 2.1.2:

```ruby
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):003:0> Vips::VERSION
=> "2.1.2"
irb(main):005:0> Vips::version 0
=> 8
irb(main):004:0> Vips::version 1
=> 9
irb(main):007:0> x = Vips::Image.new_from_file "upload.pdf", access: :sequential
irb(main):008:0> x.write_to_file "x.jpg"
irb(main):009:0>
```

It's a huge image, could it just be running out of RAM? What platform are you using?

**Comment by jcupitt** [comment]
I see:

```
$ /usr/bin/time -f %M:%e vips copy upload.pdf x.jpg
2250080:49.41
```

ie. it needs 2.2GB of memory for the conversion.

**Comment by jcupitt** [comment]
Oh, it's a bit less if I turn concurrency down:

```
$ /usr/bin/time -f %M:%e vips copy upload.pdf x.jpg --vips-concurrency=1
1928140:55.01
```

"only" 1.9GB.
