### ISSUE TITLE
Operations with destructive mode

### ISSUE THREAD

**Issue by a3mar** [libvips/ruby-vips#302]
Hello!

How can i get list of operations supporting destructive mode (to using it inside mutate block)? After reading documentation, i thought that all operations can be used like that 

    img.mutate do |tmp_img|
      tmp_img.resize! ratio, { kernel: :lanczos3 }
      tmp_img.embed!((size - tmp_img.width) / 2, 0, size, size, { extend: :white })
    end

but i got error
`Vips::Error - operation resize is not destructive:`
from [here](https://github.com/libvips/ruby-vips/blob/master/lib/vips/operation.rb#L131).

When using resize operation, @required_input[0][:flags] is 19, ARGUMENT_MODIFY is 128 

    [1] pry(#<Vips::Introspect>)> @required_input[0][:flags] & ARGUMENT_MODIFY == 0
    => true

Is there full list of destructive operations?

**Comment by jcupitt** [comment]
Hi @a3mar,

It's the set of draw operations plus metadata modification, so `set!`, `remove!` and:

```
$ vips -l draw
    VipsDraw (draw), draw operations
      VipsDrawink (drawink), draw with ink operations
        VipsDrawRect (draw_rect), paint a rectangle on an image
        VipsDrawMask (draw_mask), draw a mask on an image
        VipsDrawLine (draw_line), draw a line on an image
        VipsDrawCircle (draw_circle), draw a circle on an image
        VipsDrawFlood (draw_flood), flood-fill an area
      VipsDrawImage (draw_image), paint an image into another image
      VipsDrawSmudge (draw_smudge), blur a rectangle on an image
```

For resize you can just do:

```ruby
x = x.resize 0.5
```

And it'll be efficient, so you shouldn't need destructive operations.

**Comment by jcupitt** [comment]
... I've probably misunderstood your intention.

**Comment by a3mar** [comment]
No no, it's my fault, i mistakenly thought that if i'll use *all* operations as destructive inside one mutate block, i'll get lower memory footprint and more performance. Thank you for answer

**Comment by jcupitt** [comment]
Ah OK, no, it's the other way around --- destructive operations would be slower and use more memory, except for the few that draw on images.

The mutate stuff is only useful for things like drawing lines or circles, and for metadata changes.
