### ISSUE TITLE
TypeError: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by zernie** [libvips/ruby-vips#303]
**Questions or suggestions**

Version: ruby-vips (2.1.2)

**Describe the bug**
I get a `TypeError: no implicit conversion of String into Integer`

**To Reproduce**
1. call `attachment.variant(
          resize_to_limit: ["48", "48>"],
          strip: true
        ).processed`

**Expected behavior**
No TypeError 
**Screenshots**
![image](https://user-images.githubusercontent.com/1765991/119839955-39cabc80-bf0d-11eb-9301-8730383fcc3e.png)
**Additional context**
This is a solidus (3.0.1) backend dashboard, with activestorage `local` service

**Comment by jcupitt** [comment]
Hi @zernie, this isn't a libvips error, it looks like something thrown by `image_processing`.

Maybe try changing your code to:

```ruby
attachment.variant( resize_to_limit: [48, 48], strip: true ).processed
```

(just guessing)

**Comment by zernie** [comment]
@jcupitt I get a `class "strip" not found` error

**Comment by zernie** [comment]
btw, the error is gone when I'm using mini_magick as active storage variant processor

**Comment by jcupitt** [comment]
It's still not a libvips or ruby-vips issue. I would ask on ImageProcessing.
