### ISSUE TITLE
Linux and GitHub Actions

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [libvips/ruby-vips#308]
I landed here because there are multiple related issues like this [one](https://github.com/libvips/ruby-vips/issues/212)

I am using the `helaili/jekyll-action@v2` GitHub Action to deploy the site and I am getting this error:

```
 Dependency Error: Yikes! It looks like you don't have jekyll_picture_tag or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll_picture_tag gem in your Gemfile as well. The full error message from Ruby is: 'Could not open library 'glib-2.0.so.0': Error loading shared library glib-2.0.so.0: No such file or directory. Could not open library 'libglib-2.0.so.0': Error loading shared library libglib-2.0.so.0: No such file or directory' If you run into trouble, you can find helpful resources at jekyllrb.com/help/! 
``` 
Locally (Windows 10), it is working perfectly, but I am not sure why I have this error in GitHub.

I tried to install `glib-2.0` and/or `libvips` with no success.

I am using the latest version of all dependencies.

**Comment by jcupitt** [comment]
Hi @JavierSegoviaCordoba,

You can see the github action we use for ruby-vips here:

https://github.com/libvips/ruby-vips/blob/master/.github/workflows/test.yml

And it (obviously) works. Does that help? 

I would open an issue on helaili/jekyll-action@v2 if you can't get it going.

**Comment by JavierSegoviaCordoba** [comment]
Indeed I tried like 3 or 4 Jekyll actions, same issue. I am going to try your setup now to check if it works.

**Comment by JavierSegoviaCordoba** [comment]
It doesn't work for me, I will file an issue in the helaili action, but, strangely, all actions for deploying Jekyll sites to GitHub pages are failing with the same issue.

**Comment by jcupitt** [comment]
I pinged the repo and reran the action:

https://github.com/libvips/ruby-vips/runs/2887946268?check_suite_focus=true

It seems to work.

**Comment by JavierSegoviaCordoba** [comment]
Yeah, maybe a problem with helaili docker installation thank you for your help, I am going to close this issue.
