### ISSUE TITLE
ruby-vips changes the behavior of vips commands executed in irb

### ISSUE THREAD

**Issue by brenogazzola** [libvips/ruby-vips#312]
**Describe the bug**
When `ruby-vips` is loaded in a `irb` session, it changes the behavior of `vips` commands. In my use case, it is breaking the `autorot` command.

**To Reproduce**
Let's start with a photo taken in an iPhone, in portrait mode, and air dropped to a Mac, so it retains its `.heic` extension. I've taken such a photo (it's of my house, no one in view) and uploaded it to S3.

Then follow these steps:
```
$ cd /tmp
$ wget https://s3.sa-east-1.amazonaws.com/cdn.festalab.com.br/development/demo.heic
$ exiftool demo.heic | grep Orientation
=> Orientation: Rotate 90 CW

$ vips copy /tmp/demo.heic /tmp/demo_terminal.jpg
$ exiftool demo_terminal.jpg | grep Orientation
=> Orientation: Horizontal (normal)

$ irb
:0> require 'ruby-vips'
:0> `vips copy /tmp/demo.heic /tmp/demo_ruby.jpg`
:0> exit
$ exiftool demo_ruby.jpg | grep Orientation
=> Orientation: Rotate 90 CW

$ irb
:0> require 'ruby-vips'
:0> `vips autorot /tmp/demo_ruby.jpg /tmp/demo_ruby_rot.jpg`
:0> exit
$ exiftool demo_ruby_rot.jpg | grep Orientation
=> Orientation: Horizontal (normal)
```

**Expected behavior**
So here's what I'm seeing in each photo.

_demo.heic_: The original photo. If I preview it I see it in portrait mode and it looks just like I expected. It also has `Rotate 90 CW`, since that's how iPhone's set portrait photos.

_demo_terminal.jpg_: The version I converted in the terminal. If I preview it I see it in portrait mode too, just like I expected. However it no longer has a rotation in exif. That's fine.

_demo_ruby.jpg_: The version I converted in `irb`. It if preview it, it's now in landscape mode and no longer looks 'right' to me. It also still has `Rotate 90 CW`. Since I used the exact same command I used in the terminal, I'm definitely surprised I got a different result

_demo_ruby_rot.jpg_: Here I tried to "fix" the ruby photo, by using `autorot`. However, this broke the photo. It continue in landscape mode, but the exif data no longer says it's rotated.

**Screenshots**
<img width="1032" alt="vips_screenshot" src="https://user-images.githubusercontent.com/1793280/124180369-75b3ed00-da8a-11eb-933b-da723b5bb393.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Vips Version: vips-8.11.0-Wed Jun  9 18:20:35 UTC 2021 (from homebrew, `vips --version`)
 - Gem Version: 2.1.2 (`Vips::VERSION`)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 11.4.2
 - Browser: Safari

**Comment by jcupitt** [comment]
Hi @brenogazzola, could you try 8.11.1? It has a fix for (I hope) this issue.

**Comment by jcupitt** [comment]
(homebrew updated yesterday, so you should have it)

**Comment by jcupitt** [comment]
I just tried on my mac and it should be fixed in 8.11.1. I see:

```
irb(main):006:0> `vips copy demo.heic demo_ruby.jpg`
=> ""
irb(main):007:0> 
✔ ~ 
11:16 $ exiftool demo_ruby.jpg | grep Orientation
Orientation                     : Horizontal (normal)
```

ie. same behaviour as the version run from the shell.

**Comment by brenogazzola** [comment]
It works! 👍
I've been meaning to open this issue since last week and didn't notice there was a new version of vips out. Sorry about that. Second time I open an issue that's not actually an issue 😅

**Comment by jcupitt** [comment]
Great! Sorry it was broken.
