### ISSUE TITLE
API Documentation is broken

### ISSUE THREAD

**Issue by anduong** [libvips/ruby-vips#316]
In the current README.md file, I follow the link https://www.rubydoc.info/gems/ruby-vips to check out the documentation but it has issue with the gem doc. Can you please look at it? Thanks

![image](https://user-images.githubusercontent.com/6139560/130771140-1141fe95-cef8-409a-932c-65917dc6f4ca.png)

**Comment by Nakilon** [comment]
It's down for a while. And for many other gems. I believe it's a problem on the side of YARD gem website. For example: https://github.com/lsegal/yard/issues/1146

**Comment by jcupitt** [comment]
That's a shame, I hope they fix it soon.

In the meantime, you can generate the docs yourself locally with:

```
$ bundle exec rake yard
```

Then point a browser at `doc/index.html`.

**Comment by Nakilon** [comment]
`Memory 6G`? https://github.com/docmeta/rubydoc.info/commit/d3fb0c9ce09d695b898ba7372112fdbac587cc4a
I feel like the issue is in that he tries to rebuild the documentation for all the gems in the world in one run.

**Comment by Nakilon** [comment]
From the https://github.com/docmeta/rubydoc.info/commit/d3fb0c9ce09d695b898ba7372112fdbac587cc4a I suppose he either runs our of memory for his caching server where he used https://en.wikipedia.org/wiki/Varnish_(software) or there is something else I don't see.

**Comment by jcupitt** [comment]
Ouch, that's bad @Nakilon. 

@anduong, I made a copy of the docs on the gh-pages branch as a backup. This link should always work:

http://libvips.github.io/ruby-vips/

The tutorial introduction is in the `Vips` section:

http://libvips.github.io/ruby-vips/Vips.html

And added a note to the README.

**Comment by anduong** [comment]
superb! You guys are so active. Thanks a lot @jcupitt and @Nakilon
