### ISSUE TITLE
`clang: error: unsupported option '-fopenmp'`

### ISSUE THREAD

**Issue by dorianmariefr** [libvips/ruby-vips#320]
**Describe the bug**

When install ruby-vips, I get this error:

```
clang: error: unsupported option '-fopenmp'
```

**To Reproduce**

- Have `gem "vips"` in `Gemfile`
- Have `vips` and `llvm` installed
- run `bundle install`

**Expected behavior**

Compiles and installs and basically works

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - Browser Chrome
 - Version vips gem 8.11.3 

**Additional context**

I have ruby 3.0.3

**Comment by jcupitt** [comment]
Hi @dorianmariefr,

This is an unfortunate imagemagick issue -- they put `-fopenmp` (a gcc-only compiler directive) in their `.pc` file, so any project that links to imagemagick using `pkg-config` is also gcc-only.

I would configure without imagemagick, or edit their `.pc` file and remove the `-fopenmp`.

**Comment by kleisauke** [comment]
FWIW, you could try this (somewhat dangerous) workaround:
```bash
# Remove -Xpreprocessor -fopenmp in ImageMagick's pkg-config files
find $(brew --prefix imagemagick)/lib/pkgconfig -name '*.pc' -exec sed -i '' 's/-Xpreprocessor -fopenmp//g' {} \;
```
However, that didn't work the last time I tried to resolve this, see: https://github.com/libvips/libvips/pull/2202#issuecomment-823220983.

**Comment by dorianmariefr** [comment]
thanks, looks like a pain, I will stick with `image_processing`

**Comment by kleisauke** [comment]
> * Have `gem "vips"` in `Gemfile`

Shouldn't this be `gem "ruby-vips"`? Otherwise it will end up installing https://rubygems.org/gems/vips/, which shouldn't be necessary if you have libvips installed globally, I think.

**Comment by dorianmariefr** [comment]
I knew I messed up somewhere

**Comment by jcupitt** [comment]
Oh, good point. I would install libvips with homebrew, then just `gem install ruby-vips`.

```
brew install vips
gem install ruby-vips
```
