### ISSUE TITLE
Error saving jpg because it has wrong initial bytes?

### ISSUE THREAD

**Issue by brandoncc** [libvips/ruby-vips#321]
Hello,

Thanks, as always, for the awesome tools.

I have this method:

```ruby
  SCALE = 4
  IMAGE_OVERSIZE = 1.5

  def downscale_images(paths)
    downscale_factor = IMAGE_OVERSIZE.fdiv(SCALE)

    paths.each do |path|
      source = nil

      File.open(path, 'rb') do |file|
        source = Vips::Source.new_from_memory(file.read)
      end

      Vips::Image
        .new_from_source(source, '')
        .resize(downscale_factor, kernel: :cubic)
        .write_to_file(path)
    end
  end
```

For some reason, `#write_to_file` is throwing this error fairly often:

`Vips::Error: VipsJpeg: Not a JPEG file: starts with 0xd0 0x59`

The starting bytes are not always the same. I'm trying to figure out how to capture the image bytes for inspection by writing them to a file and send them to myself when the error happens. Is there a way that I can write the image data to a raw binary file?

Also, do you have any idea what might be happening here? It seems like if the source image was corrupted, it wouldn't make it through the `#new_from_source` and `#resize` lines...

The non-project frames in my stack trace are:

```
File /app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.1.2/lib/vips/operation.rb line 214 in build
File /app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.1.2/lib/vips/operation.rb line 469 in call
File /app/vendor/bundle/ruby/2.6.0/gems/ruby-vips-2.1.2/lib/vips/image.rb line 592 in write_to_file
```

Thank you!

**Comment by jcupitt** [comment]
Hi @brandoncc, there was an issue a bit like this, but I think it's been fixed. Which libvips are you using?

Your code would be a bit quicker and slimmer as:

```ruby
source = Vips::Source.new_from_file(path)
```

I expect you know.

**Comment by brandoncc** [comment]
I'm on version 8.10.6.

I didn't realize I could use `.new_from_file`. Thank you for that tidbit.

**Comment by brandoncc** [comment]
Thanks for the help @jcupitt, when you have a chance can you let me know what versions are affected by the bug?

**Comment by jcupitt** [comment]
It was only a vague memory and I can't see a specific commit or change note for it. I'd try 8.12 and see if the problem's still there.

Other things could cause your error. We'd need a way of reproducing this problem to be sure of the cause.

**Comment by brandoncc** [comment]
Okay, I'll do that John, thank you. I don't currently have a repro case, but that will be my next step if the problem continues.

**Comment by brandoncc** [comment]
I figured out the issue. I don't know if it would be considered a bug or not, but here is the solution and explanation:

```ruby
  def downscale_images(paths)
    downscale_factor = IMAGE_OVERSIZE.fdiv(SCALE)

    # vips can't write the same file it is reading from. We have tried using a
    # source as an intermediary but there were issues with the source file
    # being 0 bytes when #write_to_file executed.
    original_path = File.dirname(paths.first)
    downsized_path = "#{original_path}/downsized"
    FileUtils.mkdir_p(downsized_path)
    FileUtils.cp(paths, downsized_path)

    downsized_paths = paths.map do |path|
      "#{File.dirname(path)}/downsized/#{File.basename(path)}"
    end

    downsized_paths.each_with_index do |path, index|
      Vips::Image
        .new_from_file(path)
        .resize(downscale_factor, kernel: :cubic)
        .write_to_file(paths[index])
    end
  end
```

I rewrote the method I had pasted originally to this version. I was originally using `Source` because I wanted to write to the same path I was reading from. Since libvips uses a pipeline approach, the source and destination can't be the same.

I used a `Source` thinking that it would load the file content into memory and then I wouldn't have the problem anymore. It seems that the source file would be 0 bytes sometimes, throwing the error that caused me to open this issue. I updated the method to make copies of the files first so I would have completely different input and output paths, and my reproduction case seems to work fine now.
