### ISSUE TITLE
Resize and converting from `.png` (with transparent background) to `.jpg` adds a black background

### ISSUE THREAD

**Issue by GabrielLyonB** [libvips/ruby-vips#348]
Hi there 👋 ,

### Context
I'm using the [image_processing](https://github.com/janko/image_processing) gem to [`resize_and_pad`](https://github.com/janko/image_processing/blob/master/doc/vips.md#resize_and_pad) every image in my website (into different sizes and to make them lighter).
I found that there is an option to add `background` but it only applies on the remaining area of the resized image. Here is the [issue](https://github.com/janko/image_processing/issues/106) i open in that gem, but their answer brought me here. 

### My Problem
I have this one case in which, i convert a `.png` file with transparent background to a `.jpg` file. The result is a `.jpg` image with black background. 

#### Questions
1. Is this the expected behaviour?
  1.1. I this is the expected behaviour, is there a way to change the default background?
  1.2 If not, is there a way to add a background to the image?

I recognize that this question might be simply wrong because the way i which that upper level concept ("changing a backgorund") might be different from how is implemented in reality.
Also, i've been trying to read the documentation and the methods descriptions but i can't figgure out which method to use and why.
Apreciate any help.

**Comment by jcupitt** [comment]
Hello @GabrielLyonB,

The JPG saver will flatten out any alpha before writing pixels, and by default it flattens against black. You can set another colour, eg.:

```ruby
image.write_to_file "x.jpg", background: 255
```

Or maybe:

```ruby
image.write_to_file "x.jpg", background: [255, 0, 0]
```

For a red background.

**Comment by GabrielLyonB** [comment]
Thank you @jcupitt, for the quick awnser. With this i can add the `background` options to the [`saver`](https://github.com/janko/image_processing/blob/master/doc/vips.md#saver) method in the [image_processing](https://github.com/janko/image_processing) library solve my problem.
This is only added to those images that do not have a previous background set right?

**Comment by jcupitt** [comment]
It's just used to flatten out alpha, if that's what you mean.

You can also call `flatten` yourself, of course.
