### ISSUE TITLE
Lastest vips libary support

### ISSUE THREAD

**Issue by newlix** [libvips/ruby-vips#35]
Ruby-vips currently supports only up to 7.29.0.  In Mac OSX, I can't install 7.28 (lastest 7.32.1) through homebrew becuase the link http://www.vips.ecs.soton.ac.uk/supported/current/vips-7.28.0.tar.gz is dead. Can you update to support the latest library? Thanks!

**Comment by skunkworker** [comment]
@jcupitt I had this same issue on another machine, the PKG_CONFIG was set its just that libxml2 needed to be installed first. For some reason thats not a dependency anymore on either the homebrew/science vips or vips7 recipes.

https://github.com/Homebrew/homebrew-science/blob/master/vips.rb
https://github.com/Homebrew/homebrew-science/blob/master/vips7.rb

**Comment by jcupitt** [comment]
Hi again, libxml-2.0 is one of those libraries that's provided by Apple. You can install the brew version as well as the Apple version, but it's likely to cause confusion. If you can, it's much better to build against Apple's libxml-2.0.

On my machine (Yosemite), I see this:

```
$ brew uninstall libxml2
Error: No such keg: /usr/local/Cellar/libxml2
$ brew install vips
==> Installing vips from homebrew/homebrew-science
==> Downloading https://homebrew.bintray.com/bottles-science/vips-8.0.2.yosemite
Already downloaded: /Library/Caches/Homebrew/vips-8.0.2.yosemite.bottle.tar.gz
==> Pouring vips-8.0.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/vips/8.0.2: 177 files, 12M
```

ie. I have no libxml2 and vips installs from a bottle. If I look for libxml2 with `pkg-config` I see:

```
$ pkg-config --list-all | grep libxml
libxml-2.0                          libXML - libXML library version2.
$ pkg-config libxml-2.0 --cflags
-I/usr/include/libxml2 
```

So we're seeing Apple's libxml2. Apple do not supply a .pc file for libxml2 (which seems crazy to me, why bother providing headers if you won't supply a .pc file?), so homebrew has to provide them. If I do:

```
$ pkg-config --debug >& x
$ grep libxml x
File 'libxml-2.0.pc' appears to be a .pc file
Will find package 'libxml-2.0' in file '/usr/local/Library/ENV/pkgconfig/10.10/libxml-2.0.pc'
```

So homebrew has provided a .pc file for libxml2 and homebrew's `pkg-config` should find it automatically.

Unfortunately how well this works varies with homebrew version and with OS X version. If ruby-vips isn't installing, you need to track down the `libxml-2.0.pc` file on your system and make sure that `pkg-config` can see it, perhaps by setting `PKG_CONFIG_PATH`.
