### ISSUE TITLE
VipsOperation: class "icc_export" not found

### ISSUE THREAD

**Issue by travisbell** [libvips/ruby-vips#350]
Hi John,

I recently upgraded to libvips 8.13.3 and started getting the following error:

```ruby
Vips::Error - VipsOperation: class "icc_export" not found:
	/usr/local/bundle/gems/ruby-vips-2.1.4/lib/vips/operation.rb:228:in `build'
	/usr/local/bundle/gems/ruby-vips-2.1.4/lib/vips/operation.rb:483:in `call'
	/usr/local/bundle/gems/ruby-vips-2.1.4/lib/vips/image.rb:229:in `method_missing'
```

When attempting to do a call like so:

```ruby
thumbnail.thumbnail_image(750, :size => :down, :linear => true, :export_profile => 'profiles/sRGB2014.icc')
```

I was previously using 8.13.1 without any issue. Did something change in libvips?

**Comment by jcupitt** [comment]
Hi Travis,

No, I don't think anything in libvips has changed. Where did you get the binary? It sounds like it's been built without lcms support.

**Comment by travisbell** [comment]
Hi John, well that was super weird! You were right, for reasons that I can't make sense of, between my last Docker image and this one, liblcms2 was removed. Thanks for the nudge! I'll go ahead and close this.
