### ISSUE TITLE
vips cache challenges / clearing the cache for a specific file path

### ISSUE THREAD

**Issue by elohanlon** [libvips/ruby-vips#360]
Hello!

I'm using ruby-vips in a Rails app, and encountering a scenario where ruby-vips is caching a source image, so when the source image is modified and I attempt another conversion using the updated source image, the cached version is used instead of the latest source.  Although renaming the source file would solve the problem, my app derives source image file paths from resource identifiers, so I'm relying on the source file always having the same name for a given resource.

I'm reading the source image with: `img = Vips::Image.new_from_file(src_path)`

I found that using either one of these settings (individually) solves my problem and prevents caching:

`Vips.cache_set_max(0)`

`Vips.cache_set_max_files(0)`

The thing is, I'd rather not turn caching off 100% of the time in this app if I can avoid it, since there are other scenarios where I'm probably benefitting from the cache.

The best working solution I've been able to come up with so far is this:

```ruby
require 'vips'
require 'ffi'

module CustomVipsCacheControl
  extend FFI::Library

  ffi_lib library_name("vips", 42) # will this solution break if vips updates to 43?

  attach_function :vips_cache_get_max_mem, [], :int
  attach_function :vips_cache_set_max_mem, [:int], :void
  attach_function :vips_tracked_get_mem, [], :int

  def self.clear_vips_cache_mem
    puts "Memory usage before clear: #{vips_tracked_get_mem}"
    # Store original max because we'll restore it later
    original_max_value = vips_cache_get_max_mem

    # Drop max mem to 0, which also internally triggers a trim operation that clears out old cache entries
    vips_cache_set_max_mem(0)
    puts "Memory usage after clear: #{vips_tracked_get_mem}"

    # Restore original value to support future caching operations
    vips_cache_set_max_mem(original_max_value)
    puts "Restored original memory limit: #{original_max_value}"
  end
end
```

If I run `CustomVipsCacheControl.clear_vips_cache_mem` between my first and second image conversions, it clears the cache and I get the desired non-cached-read result after the second conversion.  Running `CustomVipsCacheControl.clear_vips_cache_mem` outputs the following:

```
Memory usage before clear: 66994208
Memory usage after clear: 33497104
Restored original memory limit: 104857600
```

Although `CustomVipsCacheControl.clear_vips_cache_mem` solves my problem, it would be much better if I could do a more targeted clearing of the cache for the specific file path that I'm reading in.

I have a few questions:

1) Is there a way that I could clear the cache for a specific input file path?

2) I was surprised that in my example above, "Memory usage after clear" was `33497104` and not `0`.  If I run `vips_tracked_get_mem` before performing any conversions, it outputs `0`.  Do you know why memory usage isn't getting reset to 0?

3) I took that `ffi_lib library_name("vips", 42)` line from `https://github.com/libvips/ruby-vips/blob/v2.1.4/lib/vips.rb#L573`.  Would my hard-coded `42` be something fragile that could break with future versions of libvips?

Thank you!

ruby-vips version: `2.1.4`
libvips version: `vips-8.14.1`

**Comment by jcupitt** [comment]
Hi @elohanlon,

I agree, this needs a better solution. I think a change to libvips might be the best fix, perhaps adding a `nocache` flag to the operation class to stop cache lookup for that object construction? We'd probably need to experiment.

On your questions:

1. libvips has an invalidation system which is close to what you want -- you can signal `invalidate` on an image and downstream pixel and operation cache entries are dropped. You'd want upstream though, and really only for the file format loaders.
2. Memory use includes all active objects, not just those in the cache, so you need to do a GC and nil any image references if you want to get back to 0. Something like: `GC.start; Vips::Operation.print_all` is handy to see what the cache is doing.
3. The `42` is the major library binary version number, so it'll only increment when we break back compat with eg. libvips 9.x. I doubt if that will happen for a very long time.

**Comment by jcupitt** [comment]
I made a quick libvips hack to add `nocache` option. Here's a test program:

```ruby
#!/usr/bin/ruby

require "fileutils"
require "vips"

if ARGV.length != 2
  puts "usage: ./nocache.rb IMAGE-FILE-1 IMAGE-FILE-2"
  exit 1
end

if File.exists?("fred")
  puts "file 'fred' exists, delete it first"
  exit 1
end

puts "copying #{ARGV[0]} to fred ..."
FileUtils.cp(ARGV[0], "fred")

image1 = Vips::Image.new_from_file("fred")
puts "fred.width = #{image1.width}"

puts "copying #{ARGV[1]} to fred ..."
FileUtils.cp(ARGV[1], "fred")

puts "plain image open ..."
image2 = Vips::Image.new_from_file("fred")
puts "fred.width = #{image2.width}"

puts "opening with nocache ..."
image2 = Vips::Image.new_from_file("fred", nocache: true)
puts "fred.width = #{image2.width}"

File.delete("fred")
```

With that libvips branch, I see:

```
$ ./nocache.rb ~/pics/k2.jpg ~/pics/shark.jpg 
copying /home/john/pics/k2.jpg to fred ...
fred.width = 1450
copying /home/john/pics/shark.jpg to fred ...
plain image open ...
fred.width = 1450
opening with nocache ...
fred.width = 537
```

So setting `nocache: true` on `new_from_file` makes it update the cache.

What do you think?

**Comment by elohanlon** [comment]
@jcupitt That's fantastic, thank you!  Exactly what I'm looking for!

**Comment by jcupitt** [comment]
Great!

OK, let's close this issue and continue any discussion in that PR.
