### ISSUE TITLE
Unable to save jp2k file after applying a convolution

### ISSUE THREAD

**Issue by malomalo** [libvips/ruby-vips#375]
ruby-vips reports the following error when trying to save an image with `jp2ksave` after an image has had a convolution operation applied to it:

```
Vips::Error (jp2ksave: not an integer format
):
```

**To Reproduce**
To Reproduce run the following in ruby:

```ruby
vips = ::Vips::Image.new_from_file('input.whatever')
vips = vips.thumbnail_image(100, height: 100, size: :both)
vips = vips.conv(::Vips::Image.new_from_array [[-1, -1, -1], [-1, 32, -1], [-1, -1, -1]], 24)
vips.write_to_file('output.jp2')
# => Vips::Error (jp2ksave: not an integer format
# ):
```

 - OS: MacOS 13.5.2
 - libbips: 8.14.4
-  OpenJPEG: 2.5.0

**Comment by jcupitt** [comment]
Hi @malomalo,

The jp2k saver in libvips only supports integer formats (8, 16 and 32-bits, signed and unsigned), but `conv` defaults to float output.

With your convolution mask I guess you want an integer conv, so use:

```ruby
mask = Vips::Image.new_from_array ([
  [-1, -1, -1], 
  [-1, 32, -1], 
  [-1, -1, -1]
], 24)
image = image.conv(mask, precision: :integer)
```

**Comment by malomalo** [comment]
Thanks @jcupitt I would have never guessed that, spent too much time trying to figure out what was going on.
