### ISSUE TITLE
Reduce quality image

### ISSUE THREAD

**Issue by strangerxx** [libvips/ruby-vips#376]
**Describe the bug**
After upload image reduce quality image 
Original:
![wildberries](https://github.com/libvips/ruby-vips/assets/985449/620a7aaf-c321-485b-a683-65f3178d618a)

after upload:
![wildberries (1)](https://github.com/libvips/ruby-vips/assets/985449/c6b00167-3375-4c67-8fc2-f003757ecc13)

after upload through mini_magick:
![wildberries (2)](https://github.com/libvips/ruby-vips/assets/985449/91d64888-248d-4b17-b63f-652e37a9e746)

**Server (please complete the following information):**
 - Linux: Ubuntu 20.04.5 LTS
 - rails: 7.0.8
 - ruby-vips: 2.2.0
 
**Desktop (please complete the following information):**
 - Linux: Archlinux
 - Browser chrome
 - Version  119.0.6045.159

**Comment by jcupitt** [comment]
Hello @strangerxx,

Just turn up the quality setting. For example:

```
$ vips copy berries.jpg x.jpg[Q=90]
```

To make:

![x](https://github.com/libvips/ruby-vips/assets/580843/60a891f1-daea-4d76-bbfb-1dff26b5ded9)

Though images like this should really be stored as PNG, not JPG.

**Comment by strangerxx** [comment]
> Hello @strangerxx,
> 
> Just turn up the quality setting. For example:
> 
> ```
> $ vips copy berries.jpg x.jpg[Q=90]
> ```
> 
> To make:
> 
> ![x](https://user-images.githubusercontent.com/580843/283409117-60a891f1-daea-4d76-bbfb-1dff26b5ded9.jpg)
> 
> Though images like this should really be stored as PNG, not JPG.

Thank you @jcupitt. But I don't understand why so low quality default. I will see setting Active Storage.

**Comment by jcupitt** [comment]
libvips uses the JPEG standard default of 75. You can change the default to 90, but then all your JPEG files will become huge. For example:

```
$ vips copy k2.jpg x-90.jpg[Q=90]
$ vips copy k2.jpg x-75.jpg[Q=75]
$ ls -l x*
-rw-r--r-- 1 john john 271536 Nov 16 10:58 x-75.jpg
-rw-r--r-- 1 john john 502270 Nov 16 10:58 x-90.jpg
```

A factor of two difference in filesize for this photo.

A better solution is not to use JPG for this type of image. PNG would be better quality, would maintain transparency, and would be smaller.

**Comment by strangerxx** [comment]
@jcupitt Thank you. I understand and will use other format.

**Comment by jcupitt** [comment]
For this type of small synthetic image, palette PNG is a good choice:

```
$ vips copy berries.jpg x.jpg[Q=90]
$ vips copy berries.jpg x.png[strip,palette]
$ ls -l x* 
-rw-r--r-- 1 john john   3897 Nov 16 11:02 x.jpg
-rw-r--r-- 1 john john   2937 Nov 16 11:02 x.png
```

Smaller, and looks better:

![x](https://github.com/libvips/ruby-vips/assets/580843/8bb49698-c0ff-4f6f-8ee7-3b2ae1e164eb)

**Comment by strangerxx** [comment]
@jcupitt  and webp?

**Comment by jcupitt** [comment]
It'll be bigger than palette PNG, but webp lossless is often a good choice, yes.

**Comment by strangerxx** [comment]
Ok, thank you
