### ISSUE TITLE
Random segfaults, lockups @ high CPU usage, and "read: unexpected return" messages

### ISSUE THREAD

**Issue by taylorthurlow** [libvips/ruby-vips#384]
The below reproduction script triggers a series of different issues when I run it. It generates 
a black image and then loops over a single remotely-hosted image asset and composites it some number of times with a small offset each time. Running it results in one of a few outcomes:

- A segfault (https://gist.github.com/taylorthurlow/e3c3e22b339920bace61dae586efc525, plus accompanying crash report https://gist.github.com/taylorthurlow/af4e8e72f82de5ba88481037e6abf211)
- Prints `SEGV received in BUS handler` and aborts
- The script freezes and loads up the CPU, and works until killed
- Prints `read: unexpected return` a few times and exits. Corresponding to the number of failed reads, some portion of the composited images will be the typical "broken jpg gray" but still composited into the final image.
- Occasionally, particularly with low numbers of input images, the image is rendered successfully.

The outcome does seem mostly random, but at times it does seem like the number of URLs in the input array might have some effect.

Using `VIPS_CONCURRENCY=1` does not seem to have an effect.

**To Reproduce**

```ruby
require "vips"
require "open-uri"

IMAGE_URLS = ["https://cdn.filestackcontent.com/bnTGtQw5ShqMPpxH2tMw"] * 10

image = Vips::Image.black(1500, 1500)

streams = []

IMAGE_URLS.each_with_index do |url, i|
  puts "loading #{url}"
  stream = URI.parse(url).open("rb")
  streams << stream
  source = Vips::SourceCustom.new
  source.on_read { |length| stream.read(length) }

  overlay = Vips::Image.new_from_source(source, "")

  image = image.composite2(overlay, :over, x: 50 * (i + 1), y: 50 * (i + 1))
end

image.write_to_file("output.jpg")

streams.each(&:close)
```

**Expected behavior**
No error is printed and the image is composited correctly each time it is called.

**Desktop:**
 - macOS Sonoma 14.2.1, Mac Mini M3 Pro (apple silicon)
 - Ruby 3.1, 3.2, and 3.3
 - vips 8.15.1
 - ruby-vips 2.2.0

**Comment by jcupitt** [comment]
Hi @taylorthurlow, that's a great reproducer, thank you. I'll investigate.

**Comment by jcupitt** [comment]
Great! I made a tiny PR which adds the ref, would you be able to test it?

https://github.com/libvips/ruby-vips/pull/385

Hopefully your original reproducer will now work with that change. Hopefully.

**Comment by taylorthurlow** [comment]
Just re-ran my reproducer (25 image count if relevant) and it doesn't seem to fix it. First time got a freeze then a SEGV. Confirmed that I'm running the right code with `Vips::VERSION` which gives 2.2.1.

**Comment by taylorthurlow** [comment]
Just to confirm that I was running everything as expected, I hand edited your added code and confirmed it was being called, but the left side here is actively hung up and consuming high CPU.

![CleanShot 2024-02-17 at 15 05 36@2x](https://github.com/libvips/ruby-vips/assets/761640/dac4734b-368a-4b87-8b4d-acb4354fe307)

**Comment by jcupitt** [comment]
I poked about and found a silly bug in reference handling :( I've fixed that and now your original reproducer runs well for me.

Would you have time for another quick test before I merge the PR?

**Comment by taylorthurlow** [comment]
Works great now!

**Comment by jcupitt** [comment]
Great! Now I just need to figure out why the CI is failing sigh

I think I'll just merge and hope it's a blip.

Thanks for the great reproducer. Finding things like this is very hard without a good test case, as I'm sure you know. I credited you in the changelog, let me know if that's not OK.

**Comment by taylorthurlow** [comment]
Yeah no problem about the changelog! Glad the reproducer worked well.
