### ISSUE TITLE
GLib-GObject-CRITICAL g_object_ref: assertion 'G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by deepsystm** [libvips/ruby-vips#392]
Hi!

I don't even know where to start in solving this problem.

I have this code in rails:

`avatar.variant(resize_to_fill: [100,100]).processed`

It causes an error, which I can neither catch, nor process, nor in any other way affect the code to make rails continue working. The process just terminates with an error.

Full debug log in attach.
[dbg.txt](https://github.com/libvips/ruby-vips/files/14762501/dbg.txt)

**Comment by deepsystm** [comment]
Main error is:

(rails:1136867): GLib-GObject-CRITICAL **: 17:27:22.826: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
/var/www/project/shared/bundle/ruby/3.0.0/gems/ruby-vips-2.1.4/lib/vips/operation.rb:225: [BUG] Segmentation fault at 0x00000000000000c8
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

**Comment by jcupitt** [comment]
Hi @deepsystm,

It looks like your libvips has been started up twice. This can happen (for example) if you start libvips, then fork for a query, then start it again.

Did you see https://github.com/libvips/ruby-vips/issues/155#issuecomment-1054484807 ?

I'd look at some of the other fixes in that thread as well.

**Comment by deepsystm** [comment]
> Hi @deepsystm,
> 
> It looks like your libvips has been started up twice. This can happen (for example) if you start libvips, then fork for a query, then start it again.
> 
> Did you see [#155 (comment)](https://github.com/libvips/ruby-vips/issues/155#issuecomment-1054484807) ?
> 
> I'd look at some of the other fixes in that thread as well.

Thanks for support, i will try this:

`gem 'image_processing', '~> 1.2', require: 'image_processing/vips'`

and get back with results
