### ISSUE TITLE
Dependency on the `logger` gem which will be removed in Ruby 3.5

### ISSUE THREAD

**Issue by Earlopain** [libvips/ruby-vips#397]
Same deal as with all the other gems that happened in the last few years: In Ruby 3.4 a warning will be emitted, and in 3.5 an error will be raised. https://github.com/ruby/ruby/commit/d7e558e3c48c213d0e8bedca4fb547db55613f7c

https://github.com/libvips/ruby-vips/blob/74c20e66fb5fe214f6f25b7a6e58c210bbd513fa/lib/vips.rb#L8

It must probably be added to the gemspec.

**Comment by jcupitt** [comment]
Hi @Earlopain, thanks for pointing this out. I've added logger to the gemspec.
