### ISSUE TITLE
`Vips::Image#rotate` is rotating in the opposite direction as noted by the documentation

### ISSUE THREAD

**Issue by taylorthurlow** [libvips/ruby-vips#401]
The [documentation for `#rotate`](https://www.rubydoc.info/gems/ruby-vips/Vips%2FImage:rotate) says the angle argument is a rotation amount, in degrees, counter/anti-clockwise. Calling `#rotate` with a value of `90`, for example, causes instead, a rotation of 90 degrees clockwise.

**To Reproduce**

```ruby
require "open-uri"
require "vips"

url = "https://placehold.co/1000.jpg"

Vips::Image
  .new_from_buffer(URI.open(url).read, "")
  .rotate(90)
  .write_to_file("output.jpg")

# observe the text in the image clearly rotated 90 degrees clockwise
```

**Expected behavior**

The image is rotated anti-clockwise as per the documentation (or for that matter, the documentation correctly state the rotation takes place clockwise, if that is the intended effect).

**Additional context**

- macOS 14.5 (ARM)
- `ruby-vips` 2.2.2

**Comment by jcupitt** [comment]
Hi @taylorthurlow,

Oops, you're right, it should be clockwise. The main docs are correct:

https://www.libvips.org/API/current/libvips-resample.html#vips-rotate

But the ruby docs are not. I'll fix it.

Thanks for pointing this out!

**Comment by jcupitt** [comment]
The ruby docs will be fixed next time we update the gem. Thanks again.

**Comment by taylorthurlow** [comment]
Ah... I always seem to struggle to find the appropriate libvips API docs that correspond with the Ruby API docs. I'll have to try harder next time. Thanks 👍
