### ISSUE TITLE
Vips::Image.thumbnail and Vips::Image.thumbnail_image resize to height instead of width when no hash options are present 

### ISSUE THREAD

**Issue by i-h8-github** [libvips/ruby-vips#408]
## Bug report

**Describe the bug**
`Vips::Image.thumbnail` and `Vips::Image.thumbnail_image` resize to height instead of width when no hash options are present. If a `:height` is also supplied, they will resize to the expected width

**To Reproduce**
```ruby
img = Vips::Image.new_from_file "file.pdf"
puts "#{img.width}, #{img.height}" # 612, 859
thumb = img.thumbnail_image 200
puts "#{thumb.width}, #{thumb.height}" # 142, 200
thumb = img.thumbnail_image 200, :height => 1000
puts "#{thumb.width}, #{thumb.height}" # 200, 281

thumb = Vips::Image.thumbnail "file.pdf", 200
puts "#{thumb.width}, #{thumb.height}" # 143, 200 — Different height from above for some reason
thumb = Vips::Image.thumbnail "file.pdf", 200, :height => 1000
puts "#{thumb.width}, #{thumb.height}" # 200, 281
```
**Expected behavior**
Should resize to specified width as described

**Actual behavior**
Resizes to a height of the specified width

**Environment**
 - OS: Ubuntu 24.04
 - Vips: 8.16.0

**Comment by jcupitt** [comment]
Please don't cross-post, it creates unnecessary extra work for volunteer maintainers.

See https://github.com/libvips/libvips/discussions/4312

**Comment by i-h8-github** [comment]
> Please don't cross-post, it creates unnecessary extra work for volunteer maintainers.
> 
> See [libvips/libvips#4312](https://github.com/libvips/libvips/discussions/4312)

Sorry, I wasn't sure where this belonged.

I don't understand why this is closed, though. Even if it is intended behavior, it is a bug in the behavior of ruby-vips as documented.

**Comment by jcupitt** [comment]
The ruby-vips docs are generated automatically and aren't definitive. The C docs are the real ones.

We ought to improve the ruby-vips docs. We have the main docs as marked up XML, we really ought to make something to merge them into the ruby docs. I think no one's founds the time yet.
