### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by marcelolx** [libvips/ruby-vips#409]
**Describe the bug**
I created a fresh Rails 8 app, with a `User` model that can have an avatar, and when Rails runs `ActiveStorage::AnalyzeJob` to analyze the image attached to the User, I have been seeing a segmentation fault that is happening in `ruby-vips`.

By checking some issues in this repo, I saw [this comment](https://github.com/libvips/ruby-vips/issues/264#issuecomment-756091856) from @jcupitt about the FFI gem. So, I changed my Gemfile to use the `1.16.3` version of FFI to see if it would solve the issue, and in fact, it did — The analyze job ran successfully and I haven't seen any segmentation fault anymore.

So, it seems to be something with the FFI `v1.17.0` gem, but I am opening the bug report here because I guess someone here might have a better idea of what's going on (so then we can open an issue there)

**Desktop:**
 - OS: MacOS Sequia 15.1.1 (M1)
 - Ruby: 3.3.0
 - Ruby-Vips: 2.2.2
   - FFI: 1.17.0

**Additional context**

Attached is the full stack trace of the error (too many chars to post in the issue here)

[segmentation fault.txt](https://github.com/user-attachments/files/18050225/segmentation.fault.txt)

**Comment by marcelolx** [comment]
I wonder if it is because `1.16.3` installs the ruby version while `1.17.0` seems to have the version specific for a given platform 🤔 

<img width="341" alt="image" src="https://github.com/user-attachments/assets/5781bbd0-93fd-4db5-8115-254e73801583">

**Comment by jcupitt** [comment]
Hello again,

This was working for me on macOS last time I tried :( I'll have a another go.

**Comment by jcupitt** [comment]
It all seems to work for me, sorry :( 

Where is your ruby from? I'm getting everything from homebrew:

```
11:38 $ ruby --version
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin23]
✔ ~/pics 
11:40 $ gem info ffi ruby-vips

*** LOCAL GEMS ***

ffi (1.17.0)
    Platform: arm64-darwin
    Author: Wayne Meissner
    Homepage: https://github.com/ffi/ffi/wiki
    License: BSD-3-Clause
    Installed at: /opt/homebrew/lib/ruby/gems/3.3.0

    Ruby FFI

*** LOCAL GEMS ***

ruby-vips (2.2.2)
    Author: John Cupitt
    Homepage: http://github.com/libvips/ruby-vips
    License: MIT
    Installed at: /opt/homebrew/lib/ruby/gems/3.3.0

    A fast image processing library with low memory needs
✔ ~/pics 
11:40 $ which ruby
/opt/homebrew/opt/ruby/bin/ruby
✔ ~/pics 
```

**Comment by jcupitt** [comment]
.. and I tested it with:

```

**Comment by kleisauke** [comment]
Given that the stack trace references Puma, I wonder if this relates to #155. Does the issue still occur on macOS if you set the `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=yes` environment variable?

Alternatively, you might try the workaround suggested in https://github.com/libvips/ruby-vips/issues/155#issuecomment-2010362385.

**Comment by marcelolx** [comment]
@kleisauke so I already had that environment variable set (because I was having that exact issue before)

What I did was to run `brew upgrade` to upgrade all my deps + upgrade to ruby `3.3.6` — and now it is just working with FFI v1.17 🤷 

My Ruby comes from asdf @jcupitt

Anyway guys, thanks for the hints, I guess it was something with some outdated dependency (I hadn't run `brew upgrade` for a quite long time)
