### ISSUE TITLE
Blur examples

### ISSUE THREAD

**Issue by dariocravero** [libvips/ruby-vips#60]
Hi @jcupitt,

Thanks for making this happen! :)

I wonder if you would have any snippets of code to share to apply gaussian blur to an image. I've been looking for hours and couldn't find anything online :(.

Thanks again,
Darío

**Comment by jcupitt** [comment]
I came across this old issue by accident. ruby-vips8 is finally out as a gem:

http://libvips.blogspot.co.uk/2016/01/ruby-vips-is-dead-long-live-ruby-vips8.html
